steps:
- name: 'gcr.io/cloud-builders/gcloud'
  id: deploy-decryption-function
  args:
  - functions
  - deploy
  - decryption-function
  - --runtime=python38
  - --entry-point=hello_pubsub 
  - --source=gs://test-decryption-function/source/source.zip
  - --trigger-topic=trigger-topic-customerLifetimeValueProp
  - --allow-unauthenticated
  - --region=asia-southeast2
  - --timeout=300s

- name: 'gcr.io/cloud-builders/gcloud'
  id: create-dataflow-job-cltv-prop-1
  waitFor: ['deploy-decryption-function']
  args:
  - dataflow
  - sql
  - query
  - SELECT * EXCEPT(rnd), 20 AS batch, ['nik', 'nik_or_phone', 'phone_number'] AS encrypted_cols, ['original_timestamp'] AS date_cols FROM bigquery.table.`crm-production-335312`.aixp_experiment_dev.cltv_propensity_prediction_rnd WHERE rnd >= 0 and rnd < 0.1
  - --job-name=cltv-prop-1
  - --pubsub-topic=trigger-topic-customerLifetimeValueProp
  - --region=asia-southeast2

- name: 'gcr.io/cloud-builders/gcloud'
  id: create-dataflow-job-cltv-prop-2
  waitFor: ['deploy-decryption-function']
  args:
  - dataflow
  - sql
  - query
  - SELECT * EXCEPT(rnd), 21 AS batch, ['nik', 'nik_or_phone', 'phone_number'] AS encrypted_cols, ['original_timestamp'] AS date_cols FROM bigquery.table.`crm-production-335312`.aixp_experiment_dev.cltv_propensity_prediction_rnd WHERE rnd >= 0.1 and rnd < 0.2
  - --job-name=cltv-prop-2
  - --pubsub-topic=trigger-topic-customerLifetimeValueProp
  - --region=asia-southeast2

- name: 'gcr.io/cloud-builders/gcloud'
  id: create-dataflow-job-cltv-prop-3
  waitFor: ['deploy-decryption-function']
  args:
  - dataflow
  - sql
  - query
  - SELECT * EXCEPT(rnd), 22 AS batch, ['nik', 'nik_or_phone', 'phone_number'] AS encrypted_cols, ['original_timestamp'] AS date_cols FROM bigquery.table.`crm-production-335312`.aixp_experiment_dev.cltv_propensity_prediction_rnd WHERE rnd >= 0.2 and rnd < 0.3
  - --job-name=cltv-prop-3
  - --pubsub-topic=trigger-topic-customerLifetimeValueProp
  - --region=asia-southeast2

- name: 'gcr.io/cloud-builders/gcloud'
  id: create-dataflow-job-cltv-prop-4
  waitFor: ['deploy-decryption-function']
  args:
  - dataflow
  - sql
  - query
  - SELECT * EXCEPT(rnd), 23 AS batch, ['nik', 'nik_or_phone', 'phone_number'] AS encrypted_cols, ['original_timestamp'] AS date_cols FROM bigquery.table.`crm-production-335312`.aixp_experiment_dev.cltv_propensity_prediction_rnd WHERE rnd >= 0.3 and rnd < 0.4
  - --job-name=cltv-prop-4
  - --pubsub-topic=trigger-topic-customerLifetimeValueProp
  - --region=asia-southeast2

- name: 'gcr.io/cloud-builders/gcloud'
  id: create-dataflow-job-cltv-prop-5
  waitFor: ['deploy-decryption-function']
  args:
  - dataflow
  - sql
  - query
  - SELECT * EXCEPT(rnd), 24 AS batch, ['nik', 'nik_or_phone', 'phone_number'] AS encrypted_cols, ['original_timestamp'] AS date_cols FROM bigquery.table.`crm-production-335312`.aixp_experiment_dev.cltv_propensity_prediction_rnd WHERE rnd >= 0.4 and rnd < 0.5
  - --job-name=cltv-prop-5
  - --pubsub-topic=trigger-topic-customerLifetimeValueProp
  - --region=asia-southeast2

- name: 'gcr.io/cloud-builders/gcloud'
  id: create-dataflow-job-cltv-prop-6
  waitFor: ['deploy-decryption-function']
  args:
  - dataflow
  - sql
  - query
  - SELECT * EXCEPT(rnd), 25 AS batch, ['nik', 'nik_or_phone', 'phone_number'] AS encrypted_cols, ['original_timestamp'] AS date_cols FROM bigquery.table.`crm-production-335312`.aixp_experiment_dev.cltv_propensity_prediction_rnd WHERE rnd >= 0.5 and rnd < 0.6
  - --job-name=cltv-prop-6
  - --pubsub-topic=trigger-topic-customerLifetimeValueProp
  - --region=asia-southeast2

- name: 'gcr.io/cloud-builders/gcloud'
  id: create-dataflow-job-cltv-prop-7
  waitFor: ['deploy-decryption-function']
  args:
  - dataflow
  - sql
  - query
  - SELECT * EXCEPT(rnd), 26 AS batch, ['nik', 'nik_or_phone', 'phone_number'] AS encrypted_cols, ['original_timestamp'] AS date_cols FROM bigquery.table.`crm-production-335312`.aixp_experiment_dev.cltv_propensity_prediction_rnd WHERE rnd >= 0.6 and rnd < 0.7
  - --job-name=cltv-prop-7
  - --pubsub-topic=trigger-topic-customerLifetimeValueProp
  - --region=asia-southeast2

- name: 'gcr.io/cloud-builders/gcloud'
  id: create-dataflow-job-cltv-prop-8
  waitFor: ['deploy-decryption-function']
  args:
  - dataflow
  - sql
  - query
  - SELECT * EXCEPT(rnd), 27 AS batch, ['nik', 'nik_or_phone', 'phone_number'] AS encrypted_cols, ['original_timestamp'] AS date_cols FROM bigquery.table.`crm-production-335312`.aixp_experiment_dev.cltv_propensity_prediction_rnd WHERE rnd >= 0.7 and rnd < 0.8
  - --job-name=cltv-prop-8
  - --pubsub-topic=trigger-topic-customerLifetimeValueProp
  - --region=asia-southeast2

- name: 'gcr.io/cloud-builders/gcloud'
  id: create-dataflow-job-cltv-prop-9
  waitFor: ['deploy-decryption-function']
  args:
  - dataflow
  - sql
  - query
  - SELECT * EXCEPT(rnd), 28 AS batch, ['nik', 'nik_or_phone', 'phone_number'] AS encrypted_cols, ['original_timestamp'] AS date_cols FROM bigquery.table.`crm-production-335312`.aixp_experiment_dev.cltv_propensity_prediction_rnd WHERE rnd >= 0.8 and rnd < 0.9
  - --job-name=cltv-prop-9
  - --pubsub-topic=trigger-topic-customerLifetimeValueProp
  - --region=asia-southeast2

- name: 'gcr.io/cloud-builders/gcloud'
  id: create-dataflow-job-cltv-prop-10
  waitFor: ['deploy-decryption-function']
  args:
  - dataflow
  - sql
  - query
  - SELECT * EXCEPT(rnd), 29 AS batch, ['nik', 'nik_or_phone', 'phone_number'] AS encrypted_cols, ['original_timestamp'] AS date_cols FROM bigquery.table.`crm-production-335312`.aixp_experiment_dev.cltv_propensity_prediction_rnd WHERE rnd >= 0.9
  - --job-name=cltv-prop-10
  - --pubsub-topic=trigger-topic-customerLifetimeValueProp
  - --region=asia-southeast2