steps:
- name: 'gcr.io/cloud-builders/gcloud'
  id: deploy-decryption-function-cltv
  args:
  - functions
  - deploy
  - decryption-function-cltv
  - --runtime=python38
  - --entry-point=hello_pubsub 
  - --source=gs://test-decryption-function/source/source.zip
  - --trigger-topic=trigger-topic-customerLifetimeValue
  - --allow-unauthenticated
  - --region=asia-southeast2
  - --timeout=300s

- name: 'ubuntu'
  args: ['sleep', '60']

- name: 'gcr.io/cloud-builders/gcloud'
  id: create-dataflow-job-cltv-1
  args:
  - dataflow
  - sql
  - query
  - SELECT *, 1 AS batch, ['nik', 'nik_or_phone', 'phone_number'] AS encrypted_cols, ['original_timestamp'] AS date_cols FROM bigquery.table.`crm-production-335312`.aixp_ml_prod.cltv_calculation_table_consume WHERE consumer_id < 0.05
  - --job-name=cltv-1
  - --pubsub-topic=trigger-topic-customerLifetimeValue
  - --region=asia-southeast2

- name: 'ubuntu'
  args: ['sleep', '900']

- name: 'gcr.io/cloud-builders/gcloud'
  id: create-dataflow-job-cltv-3
  args:
  - dataflow
  - sql
  - query
  - SELECT *, 3 AS batch, ['nik', 'nik_or_phone', 'phone_number'] AS encrypted_cols, ['original_timestamp'] AS date_cols FROM bigquery.table.`crm-production-335312`.aixp_ml_prod.cltv_calculation_table_consume WHERE consumer_id >= 0.1 and consumer_id < 0.15
  - --job-name=cltv-3
  - --pubsub-topic=trigger-topic-customerLifetimeValue
  - --region=asia-southeast2

- name: 'ubuntu'
  args: ['sleep', '900']

- name: 'gcr.io/cloud-builders/gcloud'
  id: create-dataflow-job-cltv-4
  args:
  - dataflow
  - sql
  - query
  - SELECT *, 4 AS batch, ['nik', 'nik_or_phone', 'phone_number'] AS encrypted_cols, ['original_timestamp'] AS date_cols FROM bigquery.table.`crm-production-335312`.aixp_ml_prod.cltv_calculation_table_consume WHERE consumer_id >= 0.15 and consumer_id < 0.2
  - --job-name=cltv-4
  - --pubsub-topic=trigger-topic-customerLifetimeValue
  - --region=asia-southeast2

- name: 'ubuntu'
  args: ['sleep', '900']

- name: 'gcr.io/cloud-builders/gcloud'
  id: create-dataflow-job-cltv-9
  args:
  - dataflow
  - sql
  - query
  - SELECT *, 9 AS batch, ['nik', 'nik_or_phone', 'phone_number'] AS encrypted_cols, ['original_timestamp'] AS date_cols FROM bigquery.table.`crm-production-335312`.aixp_ml_prod.cltv_calculation_table_consume WHERE consumer_id >= 0.4 and consumer_id < 0.45
  - --job-name=cltv-9
  - --pubsub-topic=trigger-topic-customerLifetimeValue
  - --region=asia-southeast2

- name: 'ubuntu'
  args: ['sleep', '900']

- name: 'gcr.io/cloud-builders/gcloud'
  id: create-dataflow-job-cltv-11
  args:
  - dataflow
  - sql
  - query
  - SELECT *, 11 AS batch, ['nik', 'nik_or_phone', 'phone_number'] AS encrypted_cols, ['original_timestamp'] AS date_cols FROM bigquery.table.`crm-production-335312`.aixp_ml_prod.cltv_calculation_table_consume WHERE consumer_id >= 0.5 and consumer_id < 0.55
  - --job-name=cltv-11
  - --pubsub-topic=trigger-topic-customerLifetimeValue
  - --region=asia-southeast2

- name: 'ubuntu'
  args: ['sleep', '900']

- name: 'gcr.io/cloud-builders/gcloud'
  id: create-dataflow-job-cltv-12
  args:
  - dataflow
  - sql
  - query
  - SELECT *, 12 AS batch, ['nik', 'nik_or_phone', 'phone_number'] AS encrypted_cols, ['original_timestamp'] AS date_cols FROM bigquery.table.`crm-production-335312`.aixp_ml_prod.cltv_calculation_table_consume WHERE consumer_id >= 0.55 and consumer_id < 0.6
  - --job-name=cltv-12
  - --pubsub-topic=trigger-topic-customerLifetimeValue
  - --region=asia-southeast2

- name: 'ubuntu'
  args: ['sleep', '900']

- name: 'gcr.io/cloud-builders/gcloud'
  id: create-dataflow-job-cltv-13
  args:
  - dataflow
  - sql
  - query
  - SELECT *, 13 AS batch, ['nik', 'nik_or_phone', 'phone_number'] AS encrypted_cols, ['original_timestamp'] AS date_cols FROM bigquery.table.`crm-production-335312`.aixp_ml_prod.cltv_calculation_table_consume WHERE consumer_id >= 0.6 and consumer_id < 0.65
  - --job-name=cltv-13
  - --pubsub-topic=trigger-topic-customerLifetimeValue
  - --region=asia-southeast2

- name: 'ubuntu'
  args: ['sleep', '900']

- name: 'gcr.io/cloud-builders/gcloud'
  id: create-dataflow-job-cltv-14
  args:
  - dataflow
  - sql
  - query
  - SELECT *, 14 AS batch, ['nik', 'nik_or_phone', 'phone_number'] AS encrypted_cols, ['original_timestamp'] AS date_cols FROM bigquery.table.`crm-production-335312`.aixp_ml_prod.cltv_calculation_table_consume WHERE consumer_id >= 0.65 and consumer_id < 0.7
  - --job-name=cltv-14
  - --pubsub-topic=trigger-topic-customerLifetimeValue
  - --region=asia-southeast2

- name: 'ubuntu'
  args: ['sleep', '900']

- name: 'gcr.io/cloud-builders/gcloud'
  id: create-dataflow-job-cltv-15
  args:
  - dataflow
  - sql
  - query
  - SELECT *, 15 AS batch, ['nik', 'nik_or_phone', 'phone_number'] AS encrypted_cols, ['original_timestamp'] AS date_cols FROM bigquery.table.`crm-production-335312`.aixp_ml_prod.cltv_calculation_table_consume WHERE consumer_id >= 0.7 and consumer_id < 0.75
  - --job-name=cltv-15
  - --pubsub-topic=trigger-topic-customerLifetimeValue
  - --region=asia-southeast2

- name: 'ubuntu'
  args: ['sleep', '1800']

- name: 'gcr.io/cloud-builders/gcloud'
  id: delete-deployed-function-cltv
  args:
  - functions
  - delete
  - decryption-function-cltv
  - --region=asia-southeast2

timeout: 36000s