steps:
  - name: 'gcr.io/cloud-builders/gcloud'
    id: create-dataflow-job-passion-historiTransaksi
    args:
      - dataflow
      - sql
      - query
      - SELECT *, 'historiTransaksi' AS table_name, ['nik', 'phone_number'] AS encrypted_cols, ['original_timestamp', 'import_date', 'tanggal_waktu_transaksi'] AS date_cols FROM bigquery.table.`crm-production-335312`.aixp.historiTransaksi
      - --job-name=histori-transaksi-job
      - --pubsub-topic=trigger-topic-historiTransaksi
      - --region=asia-southeast2

  - name: 'ubuntu'
    args: ['sleep', '900']

  - name: 'gcr.io/cloud-builders/gcloud'
    id: deploy-decryption-function-passion-identity
    args:
      - functions
      - deploy
      - decryption-function-passion
      - --runtime=python38
      - --entry-point=hello_pubsub
      - --source=gs://decryption-function/passion/source-passion.zip
      - --trigger-topic=trigger-topic-identity
      - --allow-unauthenticated
      - --region=asia-southeast2
      - --timeout=300s
      - --memory=256MB

  - name: 'ubuntu'
    args: ['sleep', '30']

  - name: 'gcr.io/cloud-builders/gcloud'
    id: create-dataflow-job-passion-identity
    args:
      - dataflow
      - sql
      - query
      - SELECT *, 'identity' AS table_name, ['nik', 'email', 'phone_number'] AS encrypted_cols, ['original_timestamp', 'import_date'] AS date_cols FROM bigquery.table.`crm-production-335312`.aixp.identity WHERE DATE(import_date) > '2023-01-16'
      - --job-name=identity-job
      - --pubsub-topic=trigger-topic-identity
      - --region=asia-southeast2

  - name: 'ubuntu'
    args: ['sleep', '900']

  - name: 'gcr.io/cloud-builders/gcloud'
    id: deploy-decryption-function-passion-lifestyle
    args:
      - functions
      - deploy
      - decryption-function-passion
      - --runtime=python38
      - --entry-point=hello_pubsub
      - --source=gs://decryption-function/passion/source-passion.zip
      - --trigger-topic=trigger-topic-lifestyle
      - --allow-unauthenticated
      - --region=asia-southeast2
      - --timeout=300s
      - --memory=256MB

  - name: 'ubuntu'
    args: ['sleep', '30']

  - name: 'gcr.io/cloud-builders/gcloud'
    id: create-dataflow-job-passion-lifestyle
    args:
      - dataflow
      - sql
      - query
      - SELECT *, 'lifestyle' AS table_name, ['nik'] AS encrypted_cols, ['original_timestamp', 'import_date'] AS date_cols FROM bigquery.table.`crm-production-335312`.aixp.lifestyle WHERE DATE(import_date) > '2023-01-16'
      - --job-name=lifestyle-job
      - --pubsub-topic=trigger-topic-lifestyle
      - --region=asia-southeast2

  - name: 'ubuntu'
    args: ['sleep', '900']

  - name: 'gcr.io/cloud-builders/gcloud'
    id: deploy-decryption-function-passion-pembayaranMasaDepan
    args:
      - functions
      - deploy
      - decryption-function-passion
      - --runtime=python38
      - --entry-point=hello_pubsub
      - --source=gs://decryption-function/passion/source-passion.zip
      - --trigger-topic=trigger-topic-pembayaranMasaDepan
      - --allow-unauthenticated
      - --region=asia-southeast2
      - --timeout=300s
      - --memory=256MB

  - name: 'ubuntu'
    args: ['sleep', '30']

  - name: 'gcr.io/cloud-builders/gcloud'
    id: create-dataflow-job-passion-pembayaranMasaDepan
    args:
      - dataflow
      - sql
      - query
      - SELECT *, 'pembayaranMasaDepan' AS table_name, ['nik'] AS encrypted_cols, ['original_timestamp', 'import_date', 'reminder_date', 'tanggal_jatuh_tempo'] AS date_cols FROM bigquery.table.`crm-production-335312`.aixp.pembayaranMasaDepan 
      - --job-name=pembayaranmasadepan-job
      - --pubsub-topic=trigger-topic-pembayaranMasaDepan
      - --region=asia-southeast2

  - name: 'ubuntu'
    args: ['sleep', '900']

  - name: 'gcr.io/cloud-builders/gcloud'
    id: deploy-decryption-function-passion-produkAktif
    args:
      - functions
      - deploy
      - decryption-function-passion
      - --runtime=python38
      - --entry-point=hello_pubsub
      - --source=gs://decryption-function/passion/source-passion.zip
      - --trigger-topic=trigger-topic-produkAktif
      - --allow-unauthenticated
      - --region=asia-southeast2
      - --timeout=300s
      - --memory=256MB

  - name: 'ubuntu'
    args: ['sleep', '30']

  - name: 'gcr.io/cloud-builders/gcloud'
    id: create-dataflow-job-passion-produkAktif
    args:
      - dataflow
      - sql
      - query
      - SELECT *, 'produkAktif' AS table_name, ['nik'] AS encrypted_cols, ['original_timestamp', 'import_date'] AS date_cols FROM bigquery.table.`crm-production-335312`.aixp.produkAktif_consume
      - --job-name=produkaktif-job
      - --pubsub-topic=trigger-topic-produkAktif
      - --region=asia-southeast2

  - name: 'ubuntu'
    args: ['sleep', '1200']

  - name: 'gcr.io/cloud-builders/gcloud'
    id: deploy-decryption-function-passion-profile
    args:
      - functions
      - deploy
      - decryption-function-passion
      - --runtime=python38
      - --entry-point=hello_pubsub
      - --source=gs://decryption-function/passion/source-passion.zip
      - --trigger-topic=trigger-topic-profile
      - --allow-unauthenticated
      - --region=asia-southeast2
      - --timeout=300s
      - --memory=256MB

  - name: 'ubuntu'
    args: ['sleep', '30']

  - name: 'gcr.io/cloud-builders/gcloud'
    id: create-dataflow-job-passion-profile
    args:
      - dataflow
      - sql
      - query
      - SELECT *, 'profile' AS table_name, ['nik', 'nama_lengkap'] AS encrypted_cols, ['original_timestamp', 'import_date', 'tanggal_lahir'] AS date_cols FROM bigquery.table.`crm-production-335312`.aixp.profile WHERE DATE(import_date) > '2023-01-16'
      - --job-name=profile-job
      - --pubsub-topic=trigger-topic-profile
      - --region=asia-southeast2

  - name: 'ubuntu'
    args: ['sleep', '900']

  - name: 'gcr.io/cloud-builders/gcloud'
    id: deploy-decryption-function-passion-promotion
    args:
      - functions
      - deploy
      - decryption-function-passion
      - --runtime=python38
      - --entry-point=hello_pubsub
      - --source=gs://decryption-function/passion/source-passion.zip
      - --trigger-topic=trigger-topic-promotion
      - --allow-unauthenticated
      - --region=asia-southeast2
      - --timeout=300s
      - --memory=256MB

  - name: 'ubuntu'
    args: ['sleep', '30']

  - name: 'gcr.io/cloud-builders/gcloud'
    id: create-dataflow-job-passion-promotion
    args:
      - dataflow
      - sql
      - query
      - SELECT *, 'promotion' AS table_name, ['nik'] AS encrypted_cols, ['original_timestamp', 'import_date', 'tanggal'] AS date_cols FROM bigquery.table.`crm-production-335312`.aixp.promotion
      - --job-name=promotion-job
      - --pubsub-topic=trigger-topic-promotion
      - --region=asia-southeast2

  - name: 'ubuntu'
    args: ['sleep', '900']

  # - name: 'gcr.io/cloud-builders/gcloud'
  #   id: deploy-decryption-function-passion-status
  #   args:
  #     - functions
  #     - deploy
  #     - decryption-function-passion
  #     - --runtime=python38
  #     - --entry-point=hello_pubsub
  #     - --source=gs://decryption-function/passion/source-passion.zip
  #     - --trigger-topic=trigger-topic-status
  #     - --allow-unauthenticated
  #     - --region=asia-southeast2
  #     - --timeout=300s
  #     - --memory=256MB

  # - name: 'ubuntu'
  #   args: ['sleep', '30']

  # - name: 'gcr.io/cloud-builders/gcloud'
  #   id: create-dataflow-job-passion-status
  #   args:
  #     - dataflow
  #     - sql
  #     - query
  #     - SELECT *, 'status' AS table_name, ['nik'] AS encrypted_cols, ['original_timestamp', 'import_date', 'last_unblocked'] AS date_cols FROM bigquery.table.`crm-production-335312`.aixp.status WHERE import_date > TIMESTAMP(DATETIME_SUB(DATETIME_TRUNC(CURRENT_DATETIME('Asia/Jakarta'), DAY), INTERVAL 1441 MINUTE))
  #     - --job-name=status-job
  #     - --pubsub-topic=trigger-topic-status
  #     - --region=asia-southeast2

  # - name: 'ubuntu'
  #   args: ['sleep', '900']

  - name: 'gcr.io/cloud-builders/gcloud'
    id: deploy-decryption-function-passion-statusBjdpl
    args:
      - functions
      - deploy
      - decryption-function-passion
      - --runtime=python38
      - --entry-point=hello_pubsub
      - --source=gs://decryption-function/passion/source-passion.zip
      - --trigger-topic=trigger-topic-statusBjdpl
      - --allow-unauthenticated
      - --region=asia-southeast2
      - --timeout=300s
      - --memory=256MB

  - name: 'ubuntu'
    args: ['sleep', '30']

  - name: 'gcr.io/cloud-builders/gcloud'
    id: create-dataflow-job-passion-statusBjdpl
    args:
      - dataflow
      - sql
      - query
      - SELECT *, 'statusBjdpl' AS table_name, ['nik'] AS encrypted_cols, ['original_timestamp', 'import_date'] AS date_cols FROM bigquery.table.`crm-production-335312`.aixp.statusBjdpl
      - --job-name=statusbjdpl-job
      - --pubsub-topic=trigger-topic-statusBjdpl
      - --region=asia-southeast2

  - name: 'ubuntu'
    args: ['sleep', '900']

  - name: 'gcr.io/cloud-builders/gcloud'
    id: deploy-decryption-function-passion-value
    args:
      - functions
      - deploy
      - decryption-function-passion
      - --runtime=python38
      - --entry-point=hello_pubsub
      - --source=gs://decryption-function/passion/source-passion.zip
      - --trigger-topic=trigger-topic-value
      - --allow-unauthenticated
      - --region=asia-southeast2
      - --timeout=300s
      - --memory=256MB

  - name: 'ubuntu'
    args: ['sleep', '30']

  - name: 'gcr.io/cloud-builders/gcloud'
    id: create-dataflow-job-passion-value
    args:
      - dataflow
      - sql
      - query
      - SELECT *, 'value' AS table_name, ['nik'] AS encrypted_cols, ['original_timestamp', 'import_date'] AS date_cols FROM bigquery.table.`crm-production-335312`.aixp.value
      - --job-name=value-job
      - --pubsub-topic=trigger-topic-value
      - --region=asia-southeast2

  - name: 'ubuntu'
    args: ['sleep', '900']

  - name: 'gcr.io/cloud-builders/gcloud'
    id: deploy-decryption-function-passion-valueEmas
    args:
      - functions
      - deploy
      - decryption-function-passion
      - --runtime=python38
      - --entry-point=hello_pubsub
      - --source=gs://decryption-function/passion/source-passion.zip
      - --trigger-topic=trigger-topic-valueEmas
      - --allow-unauthenticated
      - --region=asia-southeast2
      - --timeout=300s
      - --memory=256MB

  - name: 'ubuntu'
    args: ['sleep', '30']

  - name: 'gcr.io/cloud-builders/gcloud'
    id: create-dataflow-job-passion-valueEmas
    args:
      - dataflow
      - sql
      - query
      - SELECT *, 'valueEmas' AS table_name, ['nik', 'phone_number'] AS encrypted_cols, ['original_timestamp', 'import_date'] AS date_cols FROM bigquery.table.`crm-production-335312`.aixp.valueEmas
      - --job-name=value-emas-job
      - --pubsub-topic=trigger-topic-valueEmas
      - --region=asia-southeast2

  - name: 'ubuntu'
    args: ['sleep', '900']

  - name: 'gcr.io/cloud-builders/gcloud'
    id: deploy-decryption-function-passion-work
    args:
      - functions
      - deploy
      - decryption-function-passion
      - --runtime=python38
      - --entry-point=hello_pubsub
      - --source=gs://decryption-function/passion/source-passion.zip
      - --trigger-topic=trigger-topic-work
      - --allow-unauthenticated
      - --region=asia-southeast2
      - --timeout=300s
      - --memory=256MB

  - name: 'ubuntu'
    args: ['sleep', '30']

  - name: 'gcr.io/cloud-builders/gcloud'
    id: create-dataflow-job-passion-work
    args:
      - dataflow
      - sql
      - query
      - SELECT *, 'work' AS table_name, ['nik'] AS encrypted_cols, ['original_timestamp', 'import_date'] AS date_cols FROM bigquery.table.`crm-production-335312`.aixp.work WHERE DATE(import_date) > '2023-01-16'
      - --job-name=work-job
      - --pubsub-topic=trigger-topic-work
      - --region=asia-southeast2

  - name: 'ubuntu'
    args: ['sleep', '900']

  - name: 'gcr.io/cloud-builders/gcloud'
    id: deploy-decryption-function-passion-workAndBusiness
    args:
      - functions
      - deploy
      - decryption-function-passion
      - --runtime=python38
      - --entry-point=hello_pubsub
      - --source=gs://decryption-function/passion/source-passion.zip
      - --trigger-topic=trigger-topic-workAndBusiness
      - --allow-unauthenticated
      - --region=asia-southeast2
      - --timeout=300s
      - --memory=256MB

  - name: 'ubuntu'
    args: ['sleep', '30']

  - name: 'gcr.io/cloud-builders/gcloud'
    id: create-dataflow-job-passion-workAndBusiness
    args:
      - dataflow
      - sql
      - query
      - SELECT *, 'workAndBusiness' AS table_name, ['nik'] AS encrypted_cols, ['original_timestamp', 'import_date'] AS date_cols FROM bigquery.table.`crm-production-335312`.aixp.workAndBusiness
      - --job-name=work-and-business-job
      - --pubsub-topic=trigger-topic-workAndBusiness
      - --region=asia-southeast2

  - name: 'ubuntu'
    args: ['sleep', '900']

  - name: 'gcr.io/cloud-builders/gcloud'
    id: delete-deployed-function
    args:
      - functions
      - delete
      - decryption-function-passion
      - --region=asia-southeast2

  - name: 'gcr.io/cloud-builders/gcloud'
    waitFor: ['delete-deployed-function']
    entrypoint: 'bq'
    id: delete-bq-geography-consume-table
    args:
      - query
      - --use_legacy_sql=false
      - DROP TABLE `crm-production-335312`.aixp.geography_consume

  - name: 'gcr.io/cloud-builders/gcloud'
    waitFor: ['delete-deployed-function']
    entrypoint: 'bq'
    id: delete-bq-produkAktif-consume-table
    args:
      - query
      - --use_legacy_sql=false
      - DROP TABLE `crm-production-335312`.aixp.produkAktif_consume

timeout: 36000s
