steps:
  - name: 'gcr.io/cloud-builders/gcloud'
    id: deploy-decryption-function-cltv
    args:
      - functions
      - deploy
      - decryption-function-cltv
      - --runtime=python38
      - --entry-point=hello_pubsub
      - --source=gs://decryption-function/cltv/source-cltv.zip
      - --trigger-topic=trigger-topic-customerLifetimeValue
      - --allow-unauthenticated
      - --region=asia-southeast2
      - --timeout=300s
      - --memory=1024MB

  - name: 'ubuntu'
    args: ['sleep', '120']

  - name: 'gcr.io/cloud-builders/gcloud'
    id: create-dataflow-job-cltv-1
    args:
      - dataflow
      - sql
      - query
      - SELECT *, 1 AS batch, ['nik', 'nik_or_phone', 'phone_number'] AS encrypted_cols, ['original_timestamp'] AS date_cols FROM bigquery.table.`crm-production-335312`.aixp_cltv_decryption.cltv_1 WHERE consumer_id < 0.1
      - --job-name=cltv-1
      - --pubsub-topic=trigger-topic-customerLifetimeValue
      - --region=asia-southeast2

  - name: 'ubuntu'
    args: ['sleep', '720']

  - name: 'gcr.io/cloud-builders/gcloud'
    id: create-dataflow-job-cltv-2
    args:
      - dataflow
      - sql
      - query
      - SELECT *, 2 AS batch, ['nik', 'nik_or_phone', 'phone_number'] AS encrypted_cols, ['original_timestamp'] AS date_cols FROM bigquery.table.`crm-production-335312`.aixp_cltv_decryption.cltv_1 WHERE consumer_id >= 0.1 and consumer_id < 0.2
      - --job-name=cltv-2
      - --pubsub-topic=trigger-topic-customerLifetimeValue
      - --region=asia-southeast2

  - name: 'ubuntu'
    args: ['sleep', '720']

  - name: 'gcr.io/cloud-builders/gcloud'
    id: create-dataflow-job-cltv-3
    args:
      - dataflow
      - sql
      - query
      - SELECT *, 3 AS batch, ['nik', 'nik_or_phone', 'phone_number'] AS encrypted_cols, ['original_timestamp'] AS date_cols FROM bigquery.table.`crm-production-335312`.aixp_cltv_decryption.cltv_1 WHERE consumer_id >= 0.2 and consumer_id < 0.3
      - --job-name=cltv-3
      - --pubsub-topic=trigger-topic-customerLifetimeValue
      - --region=asia-southeast2

  - name: 'ubuntu'
    args: ['sleep', '720']

  - name: 'gcr.io/cloud-builders/gcloud'
    id: create-dataflow-job-cltv-4
    args:
      - dataflow
      - sql
      - query
      - SELECT *, 4 AS batch, ['nik', 'nik_or_phone', 'phone_number'] AS encrypted_cols, ['original_timestamp'] AS date_cols FROM bigquery.table.`crm-production-335312`.aixp_cltv_decryption.cltv_1 WHERE consumer_id >= 0.3 and consumer_id < 0.4
      - --job-name=cltv-4
      - --pubsub-topic=trigger-topic-customerLifetimeValue
      - --region=asia-southeast2

  - name: 'ubuntu'
    args: ['sleep', '720']

  - name: 'gcr.io/cloud-builders/gcloud'
    id: create-dataflow-job-cltv-5
    args:
      - dataflow
      - sql
      - query
      - SELECT *, 5 AS batch, ['nik', 'nik_or_phone', 'phone_number'] AS encrypted_cols, ['original_timestamp'] AS date_cols FROM bigquery.table.`crm-production-335312`.aixp_cltv_decryption.cltv_1 WHERE consumer_id >= 0.4 and consumer_id < 0.5
      - --job-name=cltv-5
      - --pubsub-topic=trigger-topic-customerLifetimeValue
      - --region=asia-southeast2

  - name: 'ubuntu'
    args: ['sleep', '1200']

  - name: 'gcr.io/cloud-builders/gcloud'
    id: delete-deployed-function-cltv
    args:
      - functions
      - delete
      - decryption-function-cltv
      - --region=asia-southeast2

timeout: 36000s
