steps:
  - name: 'gcr.io/cloud-builders/gcloud'
    id: deploy-decryption-function-passion-barangLelang
    args:
      - functions
      - deploy
      - decryption-function-passion
      - --runtime=python38
      - --entry-point=hello_pubsub
      - --source=gs://decryption-function/passion/source-passion.zip
      - --trigger-topic=trigger-topic-barangLelang
      - --allow-unauthenticated
      - --region=asia-southeast2
      - --timeout=300s
      - --memory=512MB

  - name: 'ubuntu'
    args: ['sleep', '30']

  - name: 'gcr.io/cloud-builders/gcloud'
    id: create-dataflow-job-passion-barangLelang
    args:
      - dataflow
      - sql
      - query
      - SELECT *, 'barangLelang' AS table_name, ['nik'] AS encrypted_cols, ['original_timestamp', 'import_date'] AS date_cols FROM bigquery.table.`crm-production-335312`.aixp.barangLelang WHERE import_date > '2022-07-27'
      - --job-name=barang-lelang-job
      - --pubsub-topic=trigger-topic-barangLelang
      - --region=asia-southeast2

  - name: 'ubuntu'
    args: ['sleep', '600']

  - name: 'gcr.io/cloud-builders/gcloud'
    id: deploy-decryption-function-passion-historiTransaksi
    args:
      - functions
      - deploy
      - decryption-function-passion
      - --runtime=python38
      - --entry-point=hello_pubsub
      - --source=gs://decryption-function/passion/source-passion.zip
      - --trigger-topic=trigger-topic-historiTransaksi
      - --allow-unauthenticated
      - --region=asia-southeast2
      - --timeout=300s
      - --memory=512MB

  - name: 'ubuntu'
    args: ['sleep', '30']

  - name: 'gcr.io/cloud-builders/gcloud'
    id: create-dataflow-job-passion-historiTransaksi
    args:
      - dataflow
      - sql
      - query
      - SELECT *, 'historiTransaksi' AS table_name, ['nik', 'phone_number'] AS encrypted_cols, ['original_timestamp', 'import_date', 'tanggal_waktu_transaksi'] AS date_cols FROM bigquery.table.`crm-production-335312`.aixp.historiTransaksi WHERE import_date > '2022-07-27'
      - --job-name=histori-transaksi-job
      - --pubsub-topic=trigger-topic-historiTransaksi
      - --region=asia-southeast2

  - name: 'ubuntu'
    args: ['sleep', '600']

  - name: 'gcr.io/cloud-builders/gcloud'
    id: deploy-decryption-function-passion-status
    args:
      - functions
      - deploy
      - decryption-function-passion
      - --runtime=python38
      - --entry-point=hello_pubsub
      - --source=gs://decryption-function/passion/source-passion.zip
      - --trigger-topic=trigger-topic-status
      - --allow-unauthenticated
      - --region=asia-southeast2
      - --timeout=300s
      - --memory=512MB

  - name: 'ubuntu'
    args: ['sleep', '30']

  - name: 'gcr.io/cloud-builders/gcloud'
    id: create-dataflow-job-passion-status
    args:
      - dataflow
      - sql
      - query
      - SELECT *, 'status' AS table_name, ['nik'] AS encrypted_cols, ['original_timestamp', 'import_date', 'last_unblocked'] AS date_cols FROM bigquery.table.`crm-production-335312`.aixp.status WHERE import_date > '2022-07-27'
      - --job-name=status-job
      - --pubsub-topic=trigger-topic-status
      - --region=asia-southeast2

  - name: 'ubuntu'
    args: ['sleep', '600']

  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - functions
      - delete
      - decryption-function-passion
      - --region=asia-southeast2

timeout: 36000s
