steps:
  - name: 'gcr.io/cloud-builders/gcloud'
    id: deploy-decryption-function-passion-transaksiAngsuranAngsuran
    args:
      - functions
      - deploy
      - decryption-function-passion
      - --runtime=python38
      - --entry-point=hello_pubsub
      - --source=gs://decryption-function/passion/source-passion.zip
      - --trigger-topic=trigger-topic-transaksiAngsuranAngsuran
      - --allow-unauthenticated
      - --region=asia-southeast2
      - --timeout=300s
      - --memory=1024MB

  - name: 'ubuntu'
    args: ['sleep', '30']

  - name: 'gcr.io/cloud-builders/gcloud'
    id: create-dataflow-job-passion-transaksiAngsuranAngsuran
    args:
      - dataflow
      - sql
      - query
      - SELECT *, 'transaksiAngsuranAngsuran' AS table_name, ['nik'] AS encrypted_cols, ['original_timestamp', 'import_date'] AS date_cols FROM bigquery.table.`crm-production-335312`.aixp.transaksiAngsuranAngsuran WHERE import_date > '2022-07-01'
      - --job-name=transaksiangsuranangsuran-job
      - --pubsub-topic=trigger-topic-transaksiAngsuranAngsuran
      - --region=asia-southeast2

  - name: 'ubuntu'
    args: ['sleep', '600']

  - name: 'gcr.io/cloud-builders/gcloud'
    id: deploy-decryption-function-passion-transaksiAngsuranPelunasan
    args:
      - functions
      - deploy
      - decryption-function-passion
      - --runtime=python38
      - --entry-point=hello_pubsub
      - --source=gs://decryption-function/passion/source-passion.zip
      - --trigger-topic=trigger-topic-transaksiAngsuranPelunasan
      - --allow-unauthenticated
      - --region=asia-southeast2
      - --timeout=300s
      - --memory=1024MB

  - name: 'ubuntu'
    args: ['sleep', '30']

  - name: 'gcr.io/cloud-builders/gcloud'
    id: create-dataflow-job-passion-transaksiAngsuranPelunasan
    args:
      - dataflow
      - sql
      - query
      - SELECT *, 'transaksiAngsuranPelunasan' AS table_name, ['nik'] AS encrypted_cols, ['original_timestamp', 'import_date'] AS date_cols FROM bigquery.table.`crm-production-335312`.aixp.transaksiAngsuranPelunasan WHERE import_date > '2022-07-01'
      - --job-name=transaksiangsuranpelunasan-job
      - --pubsub-topic=trigger-topic-transaksiAngsuranPelunasan
      - --region=asia-southeast2

  - name: 'ubuntu'
    args: ['sleep', '600']

  - name: 'gcr.io/cloud-builders/gcloud'
    id: deploy-decryption-function-passion-transaksiAngsuranPencairan
    args:
      - functions
      - deploy
      - decryption-function-passion
      - --runtime=python38
      - --entry-point=hello_pubsub
      - --source=gs://decryption-function/passion/source-passion.zip
      - --trigger-topic=trigger-topic-transaksiAngsuranPencairan
      - --allow-unauthenticated
      - --region=asia-southeast2
      - --timeout=300s
      - --memory=1024MB

  - name: 'ubuntu'
    args: ['sleep', '30']

  - name: 'gcr.io/cloud-builders/gcloud'
    id: create-dataflow-job-passion-transaksiAngsuranPencairan
    args:
      - dataflow
      - sql
      - query
      - SELECT *, 'transaksiAngsuranPencairan' AS table_name, ['nik'] AS encrypted_cols, ['original_timestamp', 'import_date'] AS date_cols FROM bigquery.table.`crm-production-335312`.aixp.transaksiAngsuranPencairan WHERE import_date > '2022-07-01'
      - --job-name=transaksiangsuranpencairan-job
      - --pubsub-topic=trigger-topic-transaksiAngsuranPencairan
      - --region=asia-southeast2

  - name: 'ubuntu'
    args: ['sleep', '600']

  - name: 'gcr.io/cloud-builders/gcloud'
    id: deploy-decryption-function-passion-transaksiBermasalah
    args:
      - functions
      - deploy
      - decryption-function-passion
      - --runtime=python38
      - --entry-point=hello_pubsub
      - --source=gs://decryption-function/passion/source-passion.zip
      - --trigger-topic=trigger-topic-transaksiBermasalah
      - --allow-unauthenticated
      - --region=asia-southeast2
      - --timeout=300s
      - --memory=1024MB

  - name: 'ubuntu'
    args: ['sleep', '30']

  - name: 'gcr.io/cloud-builders/gcloud'
    id: create-dataflow-job-passion-transaksiBermasalah
    args:
      - dataflow
      - sql
      - query
      - SELECT *, 'transaksiBermasalah' AS table_name, ['nik'] AS encrypted_cols, ['original_timestamp', 'import_date'] AS date_cols FROM bigquery.table.`crm-production-335312`.aixp.transaksiBermasalah WHERE import_date > '2022-07-01'
      - --job-name=transaksibermasalah-job
      - --pubsub-topic=trigger-topic-transaksiBermasalah
      - --region=asia-southeast2

  - name: 'ubuntu'
    args: ['sleep', '900']

  - name: 'gcr.io/cloud-builders/gcloud'
    id: deploy-decryption-function-passion-transaksiEmasOpen
    args:
      - functions
      - deploy
      - decryption-function-passion
      - --runtime=python38
      - --entry-point=hello_pubsub
      - --source=gs://decryption-function/passion/source-passion.zip
      - --trigger-topic=trigger-topic-transaksiEmasOpen
      - --allow-unauthenticated
      - --region=asia-southeast2
      - --timeout=300s
      - --memory=1024MB

  - name: 'ubuntu'
    args: ['sleep', '30']

  - name: 'gcr.io/cloud-builders/gcloud'
    id: create-dataflow-job-passion-transaksiEmasOpen
    args:
      - dataflow
      - sql
      - query
      - SELECT *, 'transaksiEmasOpen' AS table_name, ['nik','phone_number'] AS encrypted_cols, ['original_timestamp', 'import_date'] AS date_cols FROM bigquery.table.`crm-production-335312`.aixp.transaksiEmasOpen WHERE import_date > '2022-07-01'
      - --job-name=transaksiemasopen-job
      - --pubsub-topic=trigger-topic-transaksiEmasOpen
      - --region=asia-southeast2

  - name: 'ubuntu'
    args: ['sleep', '720']

  - name: 'gcr.io/cloud-builders/gcloud'
    id: deploy-decryption-function-passion-transaksiEmasOrder
    args:
      - functions
      - deploy
      - decryption-function-passion
      - --runtime=python38
      - --entry-point=hello_pubsub
      - --source=gs://decryption-function/passion/source-passion.zip
      - --trigger-topic=trigger-topic-transaksiEmasOrder
      - --allow-unauthenticated
      - --region=asia-southeast2
      - --timeout=300s
      - --memory=1024MB

  - name: 'ubuntu'
    args: ['sleep', '30']

  - name: 'gcr.io/cloud-builders/gcloud'
    id: create-dataflow-job-passion-transaksiEmasOrder
    args:
      - dataflow
      - sql
      - query
      - SELECT *, 'transaksiEmasOrder' AS table_name, ['nik', 'phone_number'] AS encrypted_cols, ['original_timestamp', 'import_date'] AS date_cols FROM bigquery.table.`crm-production-335312`.aixp.transaksiEmasOrder WHERE import_date > '2022-07-01'
      - --job-name=transaksiemasorder-job
      - --pubsub-topic=trigger-topic-transaksiEmasOrder
      - --region=asia-southeast2

  - name: 'ubuntu'
    args: ['sleep', '600']

  - name: 'gcr.io/cloud-builders/gcloud'
    id: deploy-decryption-function-passion-transaksiEmasPYMTAIN
    args:
      - functions
      - deploy
      - decryption-function-passion
      - --runtime=python38
      - --entry-point=hello_pubsub
      - --source=gs://decryption-function/passion/source-passion.zip
      - --trigger-topic=trigger-topic-transaksiEmasPYMTAIN
      - --allow-unauthenticated
      - --region=asia-southeast2
      - --timeout=300s
      - --memory=1024MB

  - name: 'ubuntu'
    args: ['sleep', '30']

  - name: 'gcr.io/cloud-builders/gcloud'
    id: create-dataflow-job-passion-transaksiEmasPYMTAIN
    args:
      - dataflow
      - sql
      - query
      - SELECT *, 'transaksiEmasPYMTAIN' AS table_name, ['nik','phone_number'] AS encrypted_cols, ['original_timestamp', 'import_date'] AS date_cols FROM bigquery.table.`crm-production-335312`.aixp.transaksiEmasPYMTAIN WHERE import_date > '2022-07-01'
      - --job-name=transaksiemaspymtain-job
      - --pubsub-topic=trigger-topic-transaksiEmasPYMTAIN
      - --region=asia-southeast2

  - name: 'ubuntu'
    args: ['sleep', '300']

  - name: 'gcr.io/cloud-builders/gcloud'
    id: deploy-decryption-function-passion-transaksiEmasReprint
    args:
      - functions
      - deploy
      - decryption-function-passion
      - --runtime=python38
      - --entry-point=hello_pubsub
      - --source=gs://decryption-function/passion/source-passion.zip
      - --trigger-topic=trigger-topic-transaksiEmasReprint
      - --allow-unauthenticated
      - --region=asia-southeast2
      - --timeout=300s
      - --memory=1024MB

  - name: 'ubuntu'
    args: ['sleep', '30']

  - name: 'gcr.io/cloud-builders/gcloud'
    id: create-dataflow-job-passion-transaksiEmasReprint
    args:
      - dataflow
      - sql
      - query
      - SELECT *, 'transaksiEmasReprint' AS table_name, ['nik','phone_number'] AS encrypted_cols, ['original_timestamp', 'import_date'] AS date_cols FROM bigquery.table.`crm-production-335312`.aixp.transaksiEmasReprint WHERE import_date > '2022-07-01'
      - --job-name=transaksiemasreprint-job
      - --pubsub-topic=trigger-topic-transaksiEmasReprint
      - --region=asia-southeast2

  - name: 'ubuntu'
    args: ['sleep', '600']

  - name: 'gcr.io/cloud-builders/gcloud'
    id: deploy-decryption-function-passion-transaksiEmasTransfer
    args:
      - functions
      - deploy
      - decryption-function-passion
      - --runtime=python38
      - --entry-point=hello_pubsub
      - --source=gs://decryption-function/passion/source-passion.zip
      - --trigger-topic=trigger-topic-transaksiEmasTransfer
      - --allow-unauthenticated
      - --region=asia-southeast2
      - --timeout=300s
      - --memory=1024MB

  - name: 'ubuntu'
    args: ['sleep', '30']

  - name: 'gcr.io/cloud-builders/gcloud'
    id: create-dataflow-job-passion-transaksiEmasTransfer
    args:
      - dataflow
      - sql
      - query
      - SELECT *, 'transaksiEmasTransfer' AS table_name, ['nik','phone_number'] AS encrypted_cols, ['original_timestamp', 'import_date'] AS date_cols FROM bigquery.table.`crm-production-335312`.aixp.transaksiEmasTransfer WHERE import_date > '2022-07-01'
      - --job-name=transaksiemastransfer-job
      - --pubsub-topic=trigger-topic-transaksiEmasTransfer
      - --region=asia-southeast2

  - name: 'ubuntu'
    args: ['sleep', '600']

  - name: 'gcr.io/cloud-builders/gcloud'
    id: deploy-decryption-function-passion-transaksiNonAngsuranCicil
    args:
      - functions
      - deploy
      - decryption-function-passion
      - --runtime=python38
      - --entry-point=hello_pubsub
      - --source=gs://decryption-function/passion/source-passion.zip
      - --trigger-topic=trigger-topic-transaksiNonAngsuranCicil
      - --allow-unauthenticated
      - --region=asia-southeast2
      - --timeout=300s
      - --memory=1024MB

  - name: 'ubuntu'
    args: ['sleep', '30']

  - name: 'gcr.io/cloud-builders/gcloud'
    id: create-dataflow-job-passion-transaksiNonAngsuranCicil
    args:
      - dataflow
      - sql
      - query
      - SELECT *, 'transaksiNonAngsuranCicil' AS table_name, ['nik'] AS encrypted_cols, ['original_timestamp', 'import_date'] AS date_cols FROM bigquery.table.`crm-production-335312`.aixp.transaksiNonAngsuranCicil WHERE import_date > '2022-07-01'
      - --job-name=transaksinonangsurancicil-job
      - --pubsub-topic=trigger-topic-transaksiNonAngsuranCicil
      - --region=asia-southeast2

  - name: 'ubuntu'
    args: ['sleep', '600']

  - name: 'gcr.io/cloud-builders/gcloud'
    id: deploy-decryption-function-passion-transaksiNonAngsuranMintaTambah
    args:
      - functions
      - deploy
      - decryption-function-passion
      - --runtime=python38
      - --entry-point=hello_pubsub
      - --source=gs://decryption-function/passion/source-passion.zip
      - --trigger-topic=trigger-topic-transaksiNonAngsuranMintaTambah
      - --allow-unauthenticated
      - --region=asia-southeast2
      - --timeout=300s
      - --memory=1024MB

  - name: 'ubuntu'
    args: ['sleep', '30']

  - name: 'gcr.io/cloud-builders/gcloud'
    id: create-dataflow-job-passion-transaksiNonAngsuranMintaTambah
    args:
      - dataflow
      - sql
      - query
      - SELECT *, 'transaksiNonAngsuranMintaTambah' AS table_name, ['nik'] AS encrypted_cols, ['original_timestamp', 'import_date'] AS date_cols FROM bigquery.table.`crm-production-335312`.aixp.transaksiNonAngsuranMintaTambah WHERE import_date > '2022-07-01'
      - --job-name=transaksinonangsuranmintatambah-job
      - --pubsub-topic=trigger-topic-transaksiNonAngsuranMintaTambah
      - --region=asia-southeast2

  - name: 'ubuntu'
    args: ['sleep', '600']

  - name: 'gcr.io/cloud-builders/gcloud'
    id: deploy-decryption-function-passion-transaksiNonAngsuranPencairan
    args:
      - functions
      - deploy
      - decryption-function-passion
      - --runtime=python38
      - --entry-point=hello_pubsub
      - --source=gs://decryption-function/passion/source-passion.zip
      - --trigger-topic=trigger-topic-transaksiNonAngsuranPencairan
      - --allow-unauthenticated
      - --region=asia-southeast2
      - --timeout=300s
      - --memory=1024MB

  - name: 'ubuntu'
    args: ['sleep', '30']

  - name: 'gcr.io/cloud-builders/gcloud'
    id: create-dataflow-job-passion-transaksiNonAngsuranPencairan
    args:
      - dataflow
      - sql
      - query
      - SELECT *, 'transaksiNonAngsuranPencairan' AS table_name, ['nik'] AS encrypted_cols, ['original_timestamp', 'import_date'] AS date_cols FROM bigquery.table.`crm-production-335312`.aixp.transaksiNonAngsuranPencairan WHERE import_date > '2022-07-01'
      - --job-name=transaksinonangsuranpencairan-job
      - --pubsub-topic=trigger-topic-transaksiNonAngsuranPencairan
      - --region=asia-southeast2

  - name: 'ubuntu'
    args: ['sleep', '600']

  - name: 'gcr.io/cloud-builders/gcloud'
    id: deploy-decryption-function-passion-transaksiNonAngsuranUlangGadai
    args:
      - functions
      - deploy
      - decryption-function-passion
      - --runtime=python38
      - --entry-point=hello_pubsub
      - --source=gs://decryption-function/passion/source-passion.zip
      - --trigger-topic=trigger-topic-transaksiNonAngsuranUlangGadai
      - --allow-unauthenticated
      - --region=asia-southeast2
      - --timeout=300s
      - --memory=1024MB

  - name: 'ubuntu'
    args: ['sleep', '30']

  - name: 'gcr.io/cloud-builders/gcloud'
    id: create-dataflow-job-passion-transaksiNonAngsuranUlangGadai
    args:
      - dataflow
      - sql
      - query
      - SELECT *, 'transaksiNonAngsuranUlangGadai' AS table_name, ['nik'] AS encrypted_cols, ['original_timestamp', 'import_date'] AS date_cols FROM bigquery.table.`crm-production-335312`.aixp.transaksiNonAngsuranUlangGadai WHERE import_date > '2022-07-01'
      - --job-name=transaksinonangsuranulanggadai-job
      - --pubsub-topic=trigger-topic-transaksiNonAngsuranUlangGadai
      - --region=asia-southeast2

  - name: 'ubuntu'
    args: ['sleep', '600']

  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - functions
      - delete
      - decryption-function-passion
      - --region=asia-southeast2

timeout: 36000s
