steps:
- name: 'gcr.io/cloud-builders/gcloud'
  id: deploy-decryption-function
  args:
  - functions
  - deploy
  - decryption-function
  - --runtime=python38
  - --entry-point=hello_pubsub 
  - --source=gs://test-decryption-function/source/source.zip
  - --trigger-topic=trigger-topic-customerLifetimeValue
  - --allow-unauthenticated
  - --region=asia-southeast2
  - --timeout=300s

- name: 'gcr.io/cloud-builders/gcloud'
  id: create-dataflow-job-cltv-1
  args:
  - dataflow
  - sql
  - query
  - SELECT *, 1 AS batch, ['nik', 'nik_or_phone', 'phone_number'] AS encrypted_cols, ['original_timestamp'] AS date_cols FROM bigquery.table.`crm-production-335312`.aixp_ml.cltv_calculation_table_rnd WHERE consumer_id >= 0 and consumer_id < 0.05
  - --job-name=cltv-1
  - --pubsub-topic=trigger-topic-customerLifetimeValue
  - --region=asia-southeast2

- name: 'ubuntu'
  args: ['sleep', '900']

- name: 'gcr.io/cloud-builders/gcloud'
  id: create-dataflow-job-cltv-2
  args:
  - dataflow
  - sql
  - query
  - SELECT *, 2 AS batch, ['nik', 'nik_or_phone', 'phone_number'] AS encrypted_cols, ['original_timestamp'] AS date_cols FROM bigquery.table.`crm-production-335312`.aixp_ml.cltv_calculation_table_rnd WHERE consumer_id >= 0.0.5 and consumer_id < 0.1
  - --job-name=cltv-2
  - --pubsub-topic=trigger-topic-customerLifetimeValue
  - --region=asia-southeast2

- name: 'ubuntu'
  args: ['sleep', '900']

- name: 'gcr.io/cloud-builders/gcloud'
  id: create-dataflow-job-cltv-3
  args:
  - dataflow
  - sql
  - query
  - SELECT *, 3 AS batch, ['nik', 'nik_or_phone', 'phone_number'] AS encrypted_cols, ['original_timestamp'] AS date_cols FROM bigquery.table.`crm-production-335312`.aixp_ml.cltv_calculation_table_rnd WHERE consumer_id >= 0.1 and consumer_id < 0.15
  - --job-name=cltv-3
  - --pubsub-topic=trigger-topic-customerLifetimeValue
  - --region=asia-southeast2

- name: 'ubuntu'
  args: ['sleep', '900']

- name: 'gcr.io/cloud-builders/gcloud'
  id: create-dataflow-job-cltv-4
  args:
  - dataflow
  - sql
  - query
  - SELECT *, 4 AS batch, ['nik', 'nik_or_phone', 'phone_number'] AS encrypted_cols, ['original_timestamp'] AS date_cols FROM bigquery.table.`crm-production-335312`.aixp_ml.cltv_calculation_table_rnd WHERE consumer_id >= 0.15 and consumer_id < 0.2
  - --job-name=cltv-4
  - --pubsub-topic=trigger-topic-customerLifetimeValue
  - --region=asia-southeast2

- name: 'ubuntu'
  args: ['sleep', '900']

- name: 'gcr.io/cloud-builders/gcloud'
  id: create-dataflow-job-cltv-5
  args:
  - dataflow
  - sql
  - query
  - SELECT *, 5 AS batch, ['nik', 'nik_or_phone', 'phone_number'] AS encrypted_cols, ['original_timestamp'] AS date_cols FROM bigquery.table.`crm-production-335312`.aixp_ml.cltv_calculation_table_rnd WHERE consumer_id >= 0.2 and consumer_id < 0.25
  - --job-name=cltv-5
  - --pubsub-topic=trigger-topic-customerLifetimeValue
  - --region=asia-southeast2

- name: 'ubuntu'
  args: ['sleep', '900']

- name: 'gcr.io/cloud-builders/gcloud'
  id: create-dataflow-job-cltv-6
  args:
  - dataflow
  - sql
  - query
  - SELECT *, 6 AS batch, ['nik', 'nik_or_phone', 'phone_number'] AS encrypted_cols, ['original_timestamp'] AS date_cols FROM bigquery.table.`crm-production-335312`.aixp_ml.cltv_calculation_table_rnd WHERE consumer_id >= 0.25 and consumer_id < 0.3
  - --job-name=cltv-6
  - --pubsub-topic=trigger-topic-customerLifetimeValue
  - --region=asia-southeast2

- name: 'ubuntu'
  args: ['sleep', '900']

- name: 'gcr.io/cloud-builders/gcloud'
  id: create-dataflow-job-cltv-7
  args:
  - dataflow
  - sql
  - query
  - SELECT *, 7 AS batch, ['nik', 'nik_or_phone', 'phone_number'] AS encrypted_cols, ['original_timestamp'] AS date_cols FROM bigquery.table.`crm-production-335312`.aixp_ml.cltv_calculation_table_rnd WHERE consumer_id >= 0.3 and consumer_id < 0.35
  - --job-name=cltv-7
  - --pubsub-topic=trigger-topic-customerLifetimeValue
  - --region=asia-southeast2

- name: 'ubuntu'
  args: ['sleep', '900']

- name: 'gcr.io/cloud-builders/gcloud'
  id: create-dataflow-job-cltv-8
  args:
  - dataflow
  - sql
  - query
  - SELECT *, 8 AS batch, ['nik', 'nik_or_phone', 'phone_number'] AS encrypted_cols, ['original_timestamp'] AS date_cols FROM bigquery.table.`crm-production-335312`.aixp_ml.cltv_calculation_table_rnd WHERE consumer_id >= 0.35 and consumer_id < 0.4
  - --job-name=cltv-8
  - --pubsub-topic=trigger-topic-customerLifetimeValue
  - --region=asia-southeast2

- name: 'ubuntu'
  args: ['sleep', '900']

- name: 'gcr.io/cloud-builders/gcloud'
  id: create-dataflow-job-cltv-9
  args:
  - dataflow
  - sql
  - query
  - SELECT *, 9 AS batch, ['nik', 'nik_or_phone', 'phone_number'] AS encrypted_cols, ['original_timestamp'] AS date_cols FROM bigquery.table.`crm-production-335312`.aixp_ml.cltv_calculation_table_rnd WHERE consumer_id >= 0.4 and consumer_id < 0.45
  - --job-name=cltv-9
  - --pubsub-topic=trigger-topic-customerLifetimeValue
  - --region=asia-southeast2

- name: 'ubuntu'
  args: ['sleep', '900']

- name: 'gcr.io/cloud-builders/gcloud'
  id: create-dataflow-job-cltv-10
  args:
  - dataflow
  - sql
  - query
  - SELECT *, 10 AS batch, ['nik', 'nik_or_phone', 'phone_number'] AS encrypted_cols, ['original_timestamp'] AS date_cols FROM bigquery.table.`crm-production-335312`.aixp_ml.cltv_calculation_table_rnd WHERE consumer_id >= 0.45 and consumer_id < 0.5
  - --job-name=cltv-10
  - --pubsub-topic=trigger-topic-customerLifetimeValue
  - --region=asia-southeast2

- name: 'ubuntu'
  args: ['sleep', '900']

- name: 'gcr.io/cloud-builders/gcloud'
  id: create-dataflow-job-cltv-11
  args:
  - dataflow
  - sql
  - query
  - SELECT *, 11 AS batch, ['nik', 'nik_or_phone', 'phone_number'] AS encrypted_cols, ['original_timestamp'] AS date_cols FROM bigquery.table.`crm-production-335312`.aixp_ml.cltv_calculation_table_rnd WHERE consumer_id >= 0.5 and consumer_id < 0.55
  - --job-name=cltv-11
  - --pubsub-topic=trigger-topic-customerLifetimeValue
  - --region=asia-southeast2

- name: 'ubuntu'
  args: ['sleep', '900']

- name: 'gcr.io/cloud-builders/gcloud'
  id: create-dataflow-job-cltv-12
  args:
  - dataflow
  - sql
  - query
  - SELECT *, 12 AS batch, ['nik', 'nik_or_phone', 'phone_number'] AS encrypted_cols, ['original_timestamp'] AS date_cols FROM bigquery.table.`crm-production-335312`.aixp_ml.cltv_calculation_table_rnd WHERE consumer_id >= 0.55 and consumer_id < 0.6
  - --job-name=cltv-12
  - --pubsub-topic=trigger-topic-customerLifetimeValue
  - --region=asia-southeast2

- name: 'ubuntu'
  args: ['sleep', '900']

- name: 'gcr.io/cloud-builders/gcloud'
  id: create-dataflow-job-cltv-13
  args:
  - dataflow
  - sql
  - query
  - SELECT *, 13 AS batch, ['nik', 'nik_or_phone', 'phone_number'] AS encrypted_cols, ['original_timestamp'] AS date_cols FROM bigquery.table.`crm-production-335312`.aixp_ml.cltv_calculation_table_rnd WHERE consumer_id >= 0.6 and consumer_id < 0.65
  - --job-name=cltv-13
  - --pubsub-topic=trigger-topic-customerLifetimeValue
  - --region=asia-southeast2

- name: 'ubuntu'
  args: ['sleep', '900']

- name: 'gcr.io/cloud-builders/gcloud'
  id: create-dataflow-job-cltv-14
  args:
  - dataflow
  - sql
  - query
  - SELECT *, 14 AS batch, ['nik', 'nik_or_phone', 'phone_number'] AS encrypted_cols, ['original_timestamp'] AS date_cols FROM bigquery.table.`crm-production-335312`.aixp_ml.cltv_calculation_table_rnd WHERE consumer_id >= 0.65 and consumer_id < 0.7
  - --job-name=cltv-14
  - --pubsub-topic=trigger-topic-customerLifetimeValue
  - --region=asia-southeast2

- name: 'ubuntu'
  args: ['sleep', '900']

- name: 'gcr.io/cloud-builders/gcloud'
  id: create-dataflow-job-cltv-15
  args:
  - dataflow
  - sql
  - query
  - SELECT *, 15 AS batch, ['nik', 'nik_or_phone', 'phone_number'] AS encrypted_cols, ['original_timestamp'] AS date_cols FROM bigquery.table.`crm-production-335312`.aixp_ml.cltv_calculation_table_rnd WHERE consumer_id >= 0.7 and consumer_id < 0.75
  - --job-name=cltv-15
  - --pubsub-topic=trigger-topic-customerLifetimeValue
  - --region=asia-southeast2

- name: 'ubuntu'
  args: ['sleep', '900']

- name: 'gcr.io/cloud-builders/gcloud'
  id: create-dataflow-job-cltv-16
  args:
  - dataflow
  - sql
  - query
  - SELECT *, 16 AS batch, ['nik', 'nik_or_phone', 'phone_number'] AS encrypted_cols, ['original_timestamp'] AS date_cols FROM bigquery.table.`crm-production-335312`.aixp_ml.cltv_calculation_table_rnd WHERE consumer_id >= 0.75 and consumer_id < 0.8
  - --job-name=cltv-16
  - --pubsub-topic=trigger-topic-customerLifetimeValue
  - --region=asia-southeast2

- name: 'ubuntu'
  args: ['sleep', '900']

- name: 'gcr.io/cloud-builders/gcloud'
  id: create-dataflow-job-cltv-17
  args:
  - dataflow
  - sql
  - query
  - SELECT *, 17 AS batch, ['nik', 'nik_or_phone', 'phone_number'] AS encrypted_cols, ['original_timestamp'] AS date_cols FROM bigquery.table.`crm-production-335312`.aixp_ml.cltv_calculation_table_rnd WHERE consumer_id >= 0.8 and consumer_id < 0.85
  - --job-name=cltv-17
  - --pubsub-topic=trigger-topic-customerLifetimeValue
  - --region=asia-southeast2

- name: 'ubuntu'
  args: ['sleep', '900']

- name: 'gcr.io/cloud-builders/gcloud'
  id: create-dataflow-job-cltv-18
  args:
  - dataflow
  - sql
  - query
  - SELECT *, 18 AS batch, ['nik', 'nik_or_phone', 'phone_number'] AS encrypted_cols, ['original_timestamp'] AS date_cols FROM bigquery.table.`crm-production-335312`.aixp_ml.cltv_calculation_table_rnd WHERE consumer_id >= 0.85 and consumer_id < 0.9
  - --job-name=cltv-18
  - --pubsub-topic=trigger-topic-customerLifetimeValue
  - --region=asia-southeast2

- name: 'ubuntu'
  args: ['sleep', '900']

- name: 'gcr.io/cloud-builders/gcloud'
  id: create-dataflow-job-cltv-19
  args:
  - dataflow
  - sql
  - query
  - SELECT *, 19 AS batch, ['nik', 'nik_or_phone', 'phone_number'] AS encrypted_cols, ['original_timestamp'] AS date_cols FROM bigquery.table.`crm-production-335312`.aixp_ml.cltv_calculation_table_rnd WHERE consumer_id >= 0.9 and consumer_id < 0.95
  - --job-name=cltv-19
  - --pubsub-topic=trigger-topic-customerLifetimeValue
  - --region=asia-southeast2

- name: 'ubuntu'
  args: ['sleep', '900']

- name: 'gcr.io/cloud-builders/gcloud'
  id: create-dataflow-job-cltv-20
  args:
  - dataflow
  - sql
  - query
  - SELECT *, 20 AS batch, ['nik', 'nik_or_phone', 'phone_number'] AS encrypted_cols, ['original_timestamp'] AS date_cols FROM bigquery.table.`crm-production-335312`.aixp_ml.cltv_calculation_table_rnd WHERE consumer_id < 1.1
  - --job-name=cltv-20
  - --pubsub-topic=trigger-topic-customerLifetimeValue
  - --region=asia-southeast2

- name: 'ubuntu'
  args: ['sleep', '900']

- name: 'gcr.io/cloud-builders/gcloud'
  id: delete-deployed-function
  args:
  - functions
  - delete
  - decryption-function
  - --region=asia-southeast2

timeout: 39000s