steps:
- name: 'gcr.io/cloud-builders/gcloud'
  id: deploy-decryption-function
  args:
  - functions
  - deploy
  - decryption-function
  - --runtime=python38
  - --entry-point=hello_pubsub 
  - --source=gs://test-decryption-function/source/source.zip
  - --trigger-topic=trigger-topic-customerLifetimeValueProp
  - --allow-unauthenticated
  - --region=asia-southeast2
  - --timeout=300s

- name: 'gcr.io/cloud-builders/gcloud'
  id: create-dataflow-job-cltv-prop-1
  args:
  - dataflow
  - sql
  - query
  - SELECT *, 21 AS batch, ['nik', 'nik_or_phone', 'phone_number'] AS encrypted_cols, ['original_timestamp'] AS date_cols FROM bigquery.table.`crm-production-335312`.aixp_experiment_prod.cltv_propensity_prediction_consume WHERE consumer_id < 0.1
  - --job-name=cltv-prop-1
  - --pubsub-topic=trigger-topic-customerLifetimeValueProp
  - --region=asia-southeast2

- name: 'ubuntu'
  args: ['sleep', '720']

- name: 'gcr.io/cloud-builders/gcloud'
  id: create-dataflow-job-cltv-prop-2
  args:
  - dataflow
  - sql
  - query
  - SELECT *, 22 AS batch, ['nik', 'nik_or_phone', 'phone_number'] AS encrypted_cols, ['original_timestamp'] AS date_cols FROM bigquery.table.`crm-production-335312`.aixp_experiment_prod.cltv_propensity_prediction_consume WHERE consumer_id >= 0.1 and consumer_id < 0.2
  - --job-name=cltv-prop-2
  - --pubsub-topic=trigger-topic-customerLifetimeValueProp
  - --region=asia-southeast2

- name: 'ubuntu'
  args: ['sleep', '720']

- name: 'gcr.io/cloud-builders/gcloud'
  id: create-dataflow-job-cltv-prop-3
  args:
  - dataflow
  - sql
  - query
  - SELECT *, 23 AS batch, ['nik', 'nik_or_phone', 'phone_number'] AS encrypted_cols, ['original_timestamp'] AS date_cols FROM bigquery.table.`crm-production-335312`.aixp_experiment_prod.cltv_propensity_prediction_consume WHERE consumer_id >= 0.2 and consumer_id < 0.3
  - --job-name=cltv-prop-3
  - --pubsub-topic=trigger-topic-customerLifetimeValueProp
  - --region=asia-southeast2

- name: 'ubuntu'
  args: ['sleep', '720']

- name: 'gcr.io/cloud-builders/gcloud'
  id: create-dataflow-job-cltv-prop-4
  args:
  - dataflow
  - sql
  - query
  - SELECT *, 24 AS batch, ['nik', 'nik_or_phone', 'phone_number'] AS encrypted_cols, ['original_timestamp'] AS date_cols FROM bigquery.table.`crm-production-335312`.aixp_experiment_prod.cltv_propensity_prediction_consume WHERE consumer_id >= 0.3 and consumer_id < 0.4
  - --job-name=cltv-prop-4
  - --pubsub-topic=trigger-topic-customerLifetimeValueProp
  - --region=asia-southeast2

- name: 'ubuntu'
  args: ['sleep', '720']

- name: 'gcr.io/cloud-builders/gcloud'
  id: create-dataflow-job-cltv-prop-5
  args:
  - dataflow
  - sql
  - query
  - SELECT *, 25 AS batch, ['nik', 'nik_or_phone', 'phone_number'] AS encrypted_cols, ['original_timestamp'] AS date_cols FROM bigquery.table.`crm-production-335312`.aixp_experiment_prod.cltv_propensity_prediction_consume WHERE consumer_id >= 0.4 and consumer_id < 0.5
  - --job-name=cltv-prop-5
  - --pubsub-topic=trigger-topic-customerLifetimeValueProp
  - --region=asia-southeast2

- name: 'ubuntu'
  args: ['sleep', '720']

- name: 'gcr.io/cloud-builders/gcloud'
  id: create-dataflow-job-cltv-prop-6
  args:
  - dataflow
  - sql
  - query
  - SELECT *, 26 AS batch, ['nik', 'nik_or_phone', 'phone_number'] AS encrypted_cols, ['original_timestamp'] AS date_cols FROM bigquery.table.`crm-production-335312`.aixp_experiment_prod.cltv_propensity_prediction_consume WHERE consumer_id >= 0.5 and consumer_id < 0.6
  - --job-name=cltv-prop-6
  - --pubsub-topic=trigger-topic-customerLifetimeValueProp
  - --region=asia-southeast2

- name: 'ubuntu'
  args: ['sleep', '720']

- name: 'gcr.io/cloud-builders/gcloud'
  id: create-dataflow-job-cltv-prop-7
  args:
  - dataflow
  - sql
  - query
  - SELECT *, 27 AS batch, ['nik', 'nik_or_phone', 'phone_number'] AS encrypted_cols, ['original_timestamp'] AS date_cols FROM bigquery.table.`crm-production-335312`.aixp_experiment_prod.cltv_propensity_prediction_consume WHERE consumer_id >= 0.6 and consumer_id < 0.7
  - --job-name=cltv-prop-7
  - --pubsub-topic=trigger-topic-customerLifetimeValueProp
  - --region=asia-southeast2

- name: 'ubuntu'
  args: ['sleep', '720']

- name: 'gcr.io/cloud-builders/gcloud'
  id: create-dataflow-job-cltv-prop-8
  args:
  - dataflow
  - sql
  - query
  - SELECT *, 28 AS batch, ['nik', 'nik_or_phone', 'phone_number'] AS encrypted_cols, ['original_timestamp'] AS date_cols FROM bigquery.table.`crm-production-335312`.aixp_experiment_prod.cltv_propensity_prediction_consume WHERE consumer_id >= 0.7 and consumer_id < 0.8
  - --job-name=cltv-prop-8
  - --pubsub-topic=trigger-topic-customerLifetimeValueProp
  - --region=asia-southeast2

- name: 'ubuntu'
  args: ['sleep', '720']

- name: 'gcr.io/cloud-builders/gcloud'
  id: create-dataflow-job-cltv-prop-9
  args:
  - dataflow
  - sql
  - query
  - SELECT *, 29 AS batch, ['nik', 'nik_or_phone', 'phone_number'] AS encrypted_cols, ['original_timestamp'] AS date_cols FROM bigquery.table.`crm-production-335312`.aixp_experiment_prod.cltv_propensity_prediction_consume WHERE consumer_id >= 0.8 and consumer_id < 0.9
  - --job-name=cltv-prop-9
  - --pubsub-topic=trigger-topic-customerLifetimeValueProp
  - --region=asia-southeast2

- name: 'ubuntu'
  args: ['sleep', '720']

- name: 'gcr.io/cloud-builders/gcloud'
  id: create-dataflow-job-cltv-prop-10
  args:
  - dataflow
  - sql
  - query
  - SELECT *, 30 AS batch, ['nik', 'nik_or_phone', 'phone_number'] AS encrypted_cols, ['original_timestamp'] AS date_cols FROM bigquery.table.`crm-production-335312`.aixp_experiment_prod.cltv_propensity_prediction_consume WHERE consumer_id >= 0.9
  - --job-name=cltv-prop-10
  - --pubsub-topic=trigger-topic-customerLifetimeValueProp
  - --region=asia-southeast2

- name: 'ubuntu'
  args: ['sleep', '1800']

- name: 'gcr.io/cloud-builders/gcloud'
  id: delete-deployed-function
  args:
  - functions
  - delete
  - decryption-function
  - --region=asia-southeast2

timeout: 36000s