steps:
  - name: 'gcr.io/cloud-builders/gcloud'
    id: deploy-decryption-function-passion-barangLelang
    args:
      - functions
      - deploy
      - decryption-function-passion
      - --runtime=python38
      - --entry-point=hello_pubsub
      - --source=gs://decryption-function/passion/source-passion.zip
      - --trigger-topic=trigger-topic-barangLelang
      - --allow-unauthenticated
      - --region=asia-southeast2
      - --timeout=300s
      - --memory=1024MB

  - name: 'ubuntu'
    args: ['sleep', '120']

  - name: 'gcr.io/cloud-builders/gcloud'
    id: create-dataflow-job-passion-barangLelang
    args:
      - dataflow
      - sql
      - query
      - SELECT *, ['nik'] AS encrypted_cols, ['original_timestamp', 'import_date'] AS date_cols FROM bigquery.table.`crm-production-335312`.aixp.barangLelang WHERE import_date > '2022-07-01'
      - --job-name=barang-lelang-job
      - --pubsub-topic=trigger-topic-barangLelang
      - --region=asia-southeast2

  - name: 'ubuntu'
    args: ['sleep', '600']

  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - functions
      - delete
      - decryption-function-passion
      - --region=asia-southeast2

  - name: 'gcr.io/cloud-builders/gcloud'
    id: deploy-decryption-function-passion-contact
    args:
      - functions
      - deploy
      - decryption-function-passion
      - --runtime=python38
      - --entry-point=hello_pubsub
      - --source=gs://decryption-function/passion/source-passion.zip
      - --trigger-topic=trigger-topic-contact
      - --allow-unauthenticated
      - --region=asia-southeast2
      - --timeout=300s
      - --memory=1024MB

  - name: 'ubuntu'
    args: ['sleep', '120']

  - name: 'gcr.io/cloud-builders/gcloud'
    id: create-dataflow-job-passion-contact
    args:
      - dataflow
      - sql
      - query
      - SELECT *, ['nik', 'no_telepon_rumah'] AS encrypted_cols, ['original_timestamp', 'import_date'] AS date_cols FROM bigquery.table.`crm-production-335312`.aixp.contact WHERE import_date > '2022-07-01'
      - --job-name=contact-job
      - --pubsub-topic=trigger-topic-contact
      - --region=asia-southeast2

  - name: 'ubuntu'
    args: ['sleep', '600']

  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - functions
      - delete
      - decryption-function-passion
      - --region=asia-southeast2

  - name: 'gcr.io/cloud-builders/gcloud'
    id: deploy-decryption-function-passion-geography
    args:
      - functions
      - deploy
      - decryption-function-passion
      - --runtime=python38
      - --entry-point=hello_pubsub
      - --source=gs://decryption-function/passion/source-passion.zip
      - --trigger-topic=trigger-topic-geography
      - --allow-unauthenticated
      - --region=asia-southeast2
      - --timeout=300s
      - --memory=1024MB

  - name: 'ubuntu'
    args: ['sleep', '120']

  - name: 'gcr.io/cloud-builders/gcloud'
    id: create-dataflow-job-passion-geography
    args:
      - dataflow
      - sql
      - query
      - SELECT *, ['nik', 'alamat_ktp', 'alamat_domisili', 'kelurahan_domisili', 'kecamatan_domisili', 'kabupaten_kota_domisili', 'provinsi_domisili', 'kode_pos_domisili'] AS encrypted_cols, ['original_timestamp', 'import_date'] AS date_cols FROM bigquery.table.`crm-production-335312`.aixp.geography WHERE import_date > '2022-07-01'
      - --job-name=geography-job
      - --pubsub-topic=trigger-topic-geography
      - --region=asia-southeast2

  - name: 'ubuntu'
    args: ['sleep', '600']

  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - functions
      - delete
      - decryption-function-passion
      - --region=asia-southeast2

  - name: 'gcr.io/cloud-builders/gcloud'
    id: deploy-decryption-function-passion-historiTransaksi
    args:
      - functions
      - deploy
      - decryption-function-passion
      - --runtime=python38
      - --entry-point=hello_pubsub
      - --source=gs://decryption-function/passion/source-passion.zip
      - --trigger-topic=trigger-topic-historiTransaksi
      - --allow-unauthenticated
      - --region=asia-southeast2
      - --timeout=300s
      - --memory=1024MB

  - name: 'ubuntu'
    args: ['sleep', '120']

  - name: 'gcr.io/cloud-builders/gcloud'
    id: create-dataflow-job-passion-historiTransaksi
    args:
      - dataflow
      - sql
      - query
      - SELECT *, ['nik', 'phone_number'] AS encrypted_cols, ['original_timestamp', 'import_date', 'tanggal_waktu_transaksi'] AS date_cols FROM bigquery.table.`crm-production-335312`.aixp.historiTransaksi WHERE import_date > '2022-07-01'
      - --job-name=historiTransaksi-job
      - --pubsub-topic=trigger-topic-historiTransaksi
      - --region=asia-southeast2

  - name: 'ubuntu'
    args: ['sleep', '900']

  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - functions
      - delete
      - decryption-function-passion
      - --region=asia-southeast2

  - name: 'gcr.io/cloud-builders/gcloud'
    id: deploy-decryption-function-passion-identity
    args:
      - functions
      - deploy
      - decryption-function-passion
      - --runtime=python38
      - --entry-point=hello_pubsub
      - --source=gs://decryption-function/passion/source-passion.zip
      - --trigger-topic=trigger-topic-identity
      - --allow-unauthenticated
      - --region=asia-southeast2
      - --timeout=300s
      - --memory=1024MB

  - name: 'ubuntu'
    args: ['sleep', '120']

  - name: 'gcr.io/cloud-builders/gcloud'
    id: create-dataflow-job-passion-identity
    args:
      - dataflow
      - sql
      - query
      - SELECT *, ['nik', 'email', 'phone_number'] AS encrypted_cols, ['original_timestamp', 'import_date'] AS date_cols FROM bigquery.table.`crm-production-335312`.aixp.identity WHERE import_date > '2022-07-01'
      - --job-name=identity-job
      - --pubsub-topic=trigger-topic-identity
      - --region=asia-southeast2

  - name: 'ubuntu'
    args: ['sleep', '720']

  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - functions
      - delete
      - decryption-function-passion
      - --region=asia-southeast2

  - name: 'gcr.io/cloud-builders/gcloud'
    id: deploy-decryption-function-passion-lifestyle
    args:
      - functions
      - deploy
      - decryption-function-passion
      - --runtime=python38
      - --entry-point=hello_pubsub
      - --source=gs://decryption-function/passion/source-passion.zip
      - --trigger-topic=trigger-topic-lifestyle
      - --allow-unauthenticated
      - --region=asia-southeast2
      - --timeout=300s
      - --memory=1024MB

  - name: 'ubuntu'
    args: ['sleep', '120']

  - name: 'gcr.io/cloud-builders/gcloud'
    id: create-dataflow-job-passion-lifestyle
    args:
      - dataflow
      - sql
      - query
      - SELECT *, ['nik'] AS encrypted_cols, ['original_timestamp', 'import_date'] AS date_cols FROM bigquery.table.`crm-production-335312`.aixp.lifestyle WHERE import_date > '2022-07-01'
      - --job-name=lifestyle-job
      - --pubsub-topic=trigger-topic-lifestyle
      - --region=asia-southeast2

  - name: 'ubuntu'
    args: ['sleep', '720']

  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - functions
      - delete
      - decryption-function-passion
      - --region=asia-southeast2

  - name: 'gcr.io/cloud-builders/gcloud'
    id: deploy-decryption-function-passion-profile
    args:
      - functions
      - deploy
      - decryption-function-passion
      - --runtime=python38
      - --entry-point=hello_pubsub
      - --source=gs://decryption-function/passion/source-passion.zip
      - --trigger-topic=trigger-topic-profile
      - --allow-unauthenticated
      - --region=asia-southeast2
      - --timeout=300s
      - --memory=1024MB

  - name: 'ubuntu'
    args: ['sleep', '120']

  - name: 'gcr.io/cloud-builders/gcloud'
    id: create-dataflow-job-passion-profile
    args:
      - dataflow
      - sql
      - query
      - SELECT *, ['nik', 'nama_lengkap'] AS encrypted_cols, ['original_timestamp', 'import_date', 'tanggal_lahir'] AS date_cols FROM bigquery.table.`crm-production-335312`.aixp.profile WHERE import_date > '2022-07-01'
      - --job-name=profile-job
      - --pubsub-topic=trigger-topic-profile
      - --region=asia-southeast2

  - name: 'ubuntu'
    args: ['sleep', '600']

  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - functions
      - delete
      - decryption-function-passion
      - --region=asia-southeast2

  - name: 'gcr.io/cloud-builders/gcloud'
    id: deploy-decryption-function-passion-promotion
    args:
      - functions
      - deploy
      - decryption-function-passion
      - --runtime=python38
      - --entry-point=hello_pubsub
      - --source=gs://decryption-function/passion/source-passion.zip
      - --trigger-topic=trigger-topic-promotion
      - --allow-unauthenticated
      - --region=asia-southeast2
      - --timeout=300s
      - --memory=1024MB

  - name: 'ubuntu'
    args: ['sleep', '120']

  - name: 'gcr.io/cloud-builders/gcloud'
    id: create-dataflow-job-passion-promotion
    args:
      - dataflow
      - sql
      - query
      - SELECT *, ['nik'] AS encrypted_cols, ['original_timestamp', 'import_date', 'tanggal'] AS date_cols FROM bigquery.table.`crm-production-335312`.aixp.promotion WHERE import_date > '2022-07-01'
      - --job-name=promotion-job
      - --pubsub-topic=trigger-topic-promotion
      - --region=asia-southeast2

  - name: 'ubuntu'
    args: ['sleep', '300']

  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - functions
      - delete
      - decryption-function-passion
      - --region=asia-southeast2

  - name: 'gcr.io/cloud-builders/gcloud'
    id: deploy-decryption-function-passion-status
    args:
      - functions
      - deploy
      - decryption-function-passion
      - --runtime=python38
      - --entry-point=hello_pubsub
      - --source=gs://decryption-function/passion/source-passion.zip
      - --trigger-topic=trigger-topic-status
      - --allow-unauthenticated
      - --region=asia-southeast2
      - --timeout=300s
      - --memory=1024MB

  - name: 'ubuntu'
    args: ['sleep', '120']

  - name: 'gcr.io/cloud-builders/gcloud'
    id: create-dataflow-job-passion-status
    args:
      - dataflow
      - sql
      - query
      - SELECT *, ['nik'] AS encrypted_cols, ['original_timestamp', 'import_date', 'last_unblocked'] AS date_cols FROM bigquery.table.`crm-production-335312`.aixp.status WHERE import_date > '2022-07-01'
      - --job-name=status-job
      - --pubsub-topic=trigger-topic-status
      - --region=asia-southeast2

  - name: 'ubuntu'
    args: ['sleep', '600']

  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - functions
      - delete
      - decryption-function-passion
      - --region=asia-southeast2

  - name: 'gcr.io/cloud-builders/gcloud'
    id: deploy-decryption-function-passion-value
    args:
      - functions
      - deploy
      - decryption-function-passion
      - --runtime=python38
      - --entry-point=hello_pubsub
      - --source=gs://decryption-function/passion/source-passion.zip
      - --trigger-topic=trigger-topic-value
      - --allow-unauthenticated
      - --region=asia-southeast2
      - --timeout=300s
      - --memory=1024MB

  - name: 'ubuntu'
    args: ['sleep', '120']

  - name: 'gcr.io/cloud-builders/gcloud'
    id: create-dataflow-job-passion-value
    args:
      - dataflow
      - sql
      - query
      - SELECT *, ['nik'] AS encrypted_cols, ['original_timestamp', 'import_date'] AS date_cols FROM bigquery.table.`crm-production-335312`.aixp.value WHERE import_date > '2022-07-01'
      - --job-name=value-job
      - --pubsub-topic=trigger-topic-value
      - --region=asia-southeast2

  - name: 'ubuntu'
    args: ['sleep', '600']

  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - functions
      - delete
      - decryption-function-passion
      - --region=asia-southeast2

  - name: 'gcr.io/cloud-builders/gcloud'
    id: deploy-decryption-function-passion-valueEmas
    args:
      - functions
      - deploy
      - decryption-function-passion
      - --runtime=python38
      - --entry-point=hello_pubsub
      - --source=gs://decryption-function/passion/source-passion.zip
      - --trigger-topic=trigger-topic-valueEmas
      - --allow-unauthenticated
      - --region=asia-southeast2
      - --timeout=300s
      - --memory=1024MB

  - name: 'ubuntu'
    args: ['sleep', '120']

  - name: 'gcr.io/cloud-builders/gcloud'
    id: create-dataflow-job-passion-valueEmas
    args:
      - dataflow
      - sql
      - query
      - SELECT *, ['nik', 'phone_number'] AS encrypted_cols, ['original_timestamp', 'import_date'] AS date_cols FROM bigquery.table.`crm-production-335312`.aixp.valueEmas WHERE import_date > '2022-07-01'
      - --job-name=value-emas-job
      - --pubsub-topic=trigger-topic-valueEmas
      - --region=asia-southeast2

  - name: 'ubuntu'
    args: ['sleep', '600']

  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - functions
      - delete
      - decryption-function-passion
      - --region=asia-southeast2

  - name: 'gcr.io/cloud-builders/gcloud'
    id: deploy-decryption-function-passion-work
    args:
      - functions
      - deploy
      - decryption-function-passion
      - --runtime=python38
      - --entry-point=hello_pubsub
      - --source=gs://decryption-function/passion/source-passion.zip
      - --trigger-topic=trigger-topic-work
      - --allow-unauthenticated
      - --region=asia-southeast2
      - --timeout=300s
      - --memory=1024MB

  - name: 'ubuntu'
    args: ['sleep', '120']

  - name: 'gcr.io/cloud-builders/gcloud'
    id: create-dataflow-job-passion-work
    args:
      - dataflow
      - sql
      - query
      - SELECT *, ['nik'] AS encrypted_cols, ['original_timestamp', 'import_date'] AS date_cols FROM bigquery.table.`crm-production-335312`.aixp.work WHERE import_date > '2022-07-01'
      - --job-name=work-job
      - --pubsub-topic=trigger-topic-work
      - --region=asia-southeast2

  - name: 'ubuntu'
    args: ['sleep', '600']

  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - functions
      - delete
      - decryption-function-passion
      - --region=asia-southeast2

  - name: 'gcr.io/cloud-builders/gcloud'
    id: deploy-decryption-function-passion-workAndBusiness
    args:
      - functions
      - deploy
      - decryption-function-passion
      - --runtime=python38
      - --entry-point=hello_pubsub
      - --source=gs://decryption-function/passion/source-passion.zip
      - --trigger-topic=trigger-topic-workAndBusiness
      - --allow-unauthenticated
      - --region=asia-southeast2
      - --timeout=300s
      - --memory=1024MB

  - name: 'ubuntu'
    args: ['sleep', '120']

  - name: 'gcr.io/cloud-builders/gcloud'
    id: create-dataflow-job-passion-workAndBusiness
    args:
      - dataflow
      - sql
      - query
      - SELECT *, ['nik'] AS encrypted_cols, ['original_timestamp', 'import_date'] AS date_cols FROM bigquery.table.`crm-production-335312`.aixp.workAndBusiness WHERE import_date > '2022-07-01'
      - --job-name=work-and-business-job
      - --pubsub-topic=trigger-topic-workAndBusiness
      - --region=asia-southeast2

  - name: 'ubuntu'
    args: ['sleep', '600']

  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - functions
      - delete
      - decryption-function-passion
      - --region=asia-southeast2

timeout: 36000s
