steps:
  - name: 'gcr.io/cloud-builders/gcloud'
    id: deploy-decryption-function-passion-transaksiNonAngsuranUlangGadai
    args:
      - functions
      - deploy
      - decryption-function-passion
      - --runtime=python38
      - --entry-point=hello_pubsub
      - --source=gs://decryption-function/passion/source-passion.zip
      - --trigger-topic=trigger-topic-transaksiNonAngsuranUlangGadai
      - --allow-unauthenticated
      - --region=asia-southeast2
      - --timeout=300s
      - --memory=1024MB

  - name: 'ubuntu'
    args: ['sleep', '30']

  - name: 'gcr.io/cloud-builders/gcloud'
    id: create-dataflow-job-passion-transaksiNonAngsuranUlangGadai
    args:
      - dataflow
      - sql
      - query
      - SELECT *, 'transaksiNonAngsuranUlangGadai' AS table_name, ['nik'] AS encrypted_cols, ['original_timestamp', 'import_date'] AS date_cols FROM bigquery.table.`crm-production-335312`.aixp.transaksiNonAngsuranUlangGadai WHERE import_date > '2022-07-01'
      - --job-name=transaksinonangsuranulanggadai-job
      - --pubsub-topic=trigger-topic-transaksiNonAngsuranUlangGadai
      - --region=asia-southeast2

  - name: 'ubuntu'
    args: ['sleep', '600']

  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - functions
      - delete
      - decryption-function-passion
      - --region=asia-southeast2

timeout: 36000s
