steps:
  - name: 'gcr.io/cloud-builders/gcloud'
    id: deploy-decryption-function-passion-value
    args:
      - functions
      - deploy
      - decryption-function-passion
      - --runtime=python38
      - --entry-point=hello_pubsub
      - --source=gs://decryption-function/passion/source-passion.zip
      - --trigger-topic=trigger-topic-value
      - --allow-unauthenticated
      - --region=asia-southeast2
      - --timeout=300s
      - --memory=1024MB

  - name: 'ubuntu'
    args: ['sleep', '120']

  - name: 'gcr.io/cloud-builders/gcloud'
    id: create-dataflow-job-passion-value
    args:
      - dataflow
      - sql
      - query
      - SELECT *, ['nik'] AS encrypted_cols, ['original_timestamp', 'import_date'] AS date_cols FROM bigquery.table.`crm-production-335312`.aixp.value WHERE import_date > '2022-07-01'
      - --job-name=value-job
      - --pubsub-topic=trigger-topic-value
      - --region=asia-southeast2

  - name: 'ubuntu'
    args: ['sleep', '600']

  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - functions
      - delete
      - decryption-function-passion
      - --region=asia-southeast2

  - name: 'gcr.io/cloud-builders/gcloud'
    id: deploy-decryption-function-passion-valueEmas
    args:
      - functions
      - deploy
      - decryption-function-passion
      - --runtime=python38
      - --entry-point=hello_pubsub
      - --source=gs://decryption-function/passion/source-passion.zip
      - --trigger-topic=trigger-topic-valueEmas
      - --allow-unauthenticated
      - --region=asia-southeast2
      - --timeout=300s
      - --memory=1024MB

  - name: 'ubuntu'
    args: ['sleep', '120']

  - name: 'gcr.io/cloud-builders/gcloud'
    id: create-dataflow-job-passion-valueEmas
    args:
      - dataflow
      - sql
      - query
      - SELECT *, ['nik', 'phone_number'] AS encrypted_cols, ['original_timestamp', 'import_date'] AS date_cols FROM bigquery.table.`crm-production-335312`.aixp.valueEmas WHERE import_date > '2022-07-01'
      - --job-name=value-emas-job
      - --pubsub-topic=trigger-topic-valueEmas
      - --region=asia-southeast2

  - name: 'ubuntu'
    args: ['sleep', '600']

  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - functions
      - delete
      - decryption-function-passion
      - --region=asia-southeast2

  - name: 'gcr.io/cloud-builders/gcloud'
    id: deploy-decryption-function-passion-work
    args:
      - functions
      - deploy
      - decryption-function-passion
      - --runtime=python38
      - --entry-point=hello_pubsub
      - --source=gs://decryption-function/passion/source-passion.zip
      - --trigger-topic=trigger-topic-work
      - --allow-unauthenticated
      - --region=asia-southeast2
      - --timeout=300s
      - --memory=1024MB

  - name: 'ubuntu'
    args: ['sleep', '120']

  - name: 'gcr.io/cloud-builders/gcloud'
    id: create-dataflow-job-passion-work
    args:
      - dataflow
      - sql
      - query
      - SELECT *, ['nik'] AS encrypted_cols, ['original_timestamp', 'import_date'] AS date_cols FROM bigquery.table.`crm-production-335312`.aixp.work WHERE import_date > '2022-07-01'
      - --job-name=work-job
      - --pubsub-topic=trigger-topic-work
      - --region=asia-southeast2

  - name: 'ubuntu'
    args: ['sleep', '600']

  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - functions
      - delete
      - decryption-function-passion
      - --region=asia-southeast2

  - name: 'gcr.io/cloud-builders/gcloud'
    id: deploy-decryption-function-passion-workAndBusiness
    args:
      - functions
      - deploy
      - decryption-function-passion
      - --runtime=python38
      - --entry-point=hello_pubsub
      - --source=gs://decryption-function/passion/source-passion.zip
      - --trigger-topic=trigger-topic-workAndBusiness
      - --allow-unauthenticated
      - --region=asia-southeast2
      - --timeout=300s
      - --memory=1024MB

  - name: 'ubuntu'
    args: ['sleep', '120']

  - name: 'gcr.io/cloud-builders/gcloud'
    id: create-dataflow-job-passion-workAndBusiness
    args:
      - dataflow
      - sql
      - query
      - SELECT *, ['nik'] AS encrypted_cols, ['original_timestamp', 'import_date'] AS date_cols FROM bigquery.table.`crm-production-335312`.aixp.workAndBusiness WHERE import_date > '2022-07-01'
      - --job-name=work-and-business-job
      - --pubsub-topic=trigger-topic-workAndBusiness
      - --region=asia-southeast2

  - name: 'ubuntu'
    args: ['sleep', '600']

  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - functions
      - delete
      - decryption-function-passion
      - --region=asia-southeast2

timeout: 36000s
