steps:
  - name: 'gcr.io/cloud-builders/gcloud'
    id: deploy-decryption-function-passion-transaksiAngsuranAngsuran
    args:
      - functions
      - deploy
      - decryption-function-passion-transaksi
      - --runtime=python38
      - --entry-point=hello_pubsub
      - --source=gs://decryption-function/passion/source-passion.zip
      - --trigger-topic=trigger-topic-transaksiAngsuranAngsuran
      - --allow-unauthenticated
      - --region=asia-southeast2
      - --timeout=300s
      - --memory=512MB

  - name: 'ubuntu'
    args: ['sleep', '30']

  - name: 'gcr.io/cloud-builders/gcloud'
    id: create-dataflow-job-passion-transaksiAngsuranAngsuran
    args:
      - dataflow
      - sql
      - query
      - SELECT *, 'transaksiAngsuranAngsuran' AS table_name, ['nik'] AS encrypted_cols, ['original_timestamp', 'import_date'] AS date_cols FROM bigquery.table.`crm-production-335312`.aixp.transaksiAngsuranAngsuran WHERE import_date > '2022-07-27'
      - --job-name=transaksiangsuranangsuran-job
      - --pubsub-topic=trigger-topic-transaksiAngsuranAngsuran
      - --region=asia-southeast2

  - name: 'ubuntu'
    args: ['sleep', '600']

  - name: 'gcr.io/cloud-builders/gcloud'
    id: deploy-decryption-function-passion-transaksiBermasalah
    args:
      - functions
      - deploy
      - decryption-function-passion-transaksi
      - --runtime=python38
      - --entry-point=hello_pubsub
      - --source=gs://decryption-function/passion/source-passion.zip
      - --trigger-topic=trigger-topic-transaksiBermasalah
      - --allow-unauthenticated
      - --region=asia-southeast2
      - --timeout=300s
      - --memory=512MB

  - name: 'ubuntu'
    args: ['sleep', '30']

  - name: 'gcr.io/cloud-builders/gcloud'
    id: create-dataflow-job-passion-transaksiBermasalah
    args:
      - dataflow
      - sql
      - query
      - SELECT *, 'transaksiBermasalah' AS table_name, ['nik'] AS encrypted_cols, ['original_timestamp', 'import_date'] AS date_cols FROM bigquery.table.`crm-production-335312`.aixp.transaksiBermasalah WHERE import_date > '2022-07-27'
      - --job-name=transaksibermasalah-job
      - --pubsub-topic=trigger-topic-transaksiBermasalah
      - --region=asia-southeast2

  - name: 'ubuntu'
    args: ['sleep', '600']

  - name: 'gcr.io/cloud-builders/gcloud'
    id: deploy-decryption-function-passion-transaksiEmasReprint
    args:
      - functions
      - deploy
      - decryption-function-passion-transaksi
      - --runtime=python38
      - --entry-point=hello_pubsub
      - --source=gs://decryption-function/passion/source-passion.zip
      - --trigger-topic=trigger-topic-transaksiEmasReprint
      - --allow-unauthenticated
      - --region=asia-southeast2
      - --timeout=300s
      - --memory=512MB

  - name: 'ubuntu'
    args: ['sleep', '30']

  - name: 'gcr.io/cloud-builders/gcloud'
    id: create-dataflow-job-passion-transaksiEmasReprint
    args:
      - dataflow
      - sql
      - query
      - SELECT *, 'transaksiEmasReprint' AS table_name, ['nik','phone_number'] AS encrypted_cols, ['original_timestamp', 'import_date'] AS date_cols FROM bigquery.table.`crm-production-335312`.aixp.transaksiEmasReprint WHERE import_date > '2022-07-27'
      - --job-name=transaksiemasreprint-job
      - --pubsub-topic=trigger-topic-transaksiEmasReprint
      - --region=asia-southeast2

  - name: 'ubuntu'
    args: ['sleep', '600']

  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - functions
      - delete
      - decryption-function-passion-transaksi
      - --region=asia-southeast2

timeout: 36000s
