steps:
  - name: 'gcr.io/cloud-builders/gcloud'
    id: create-topic-pub-1
    args:
      - pubsub
      - topics
      - create
      - decrypt-test-1-sink
      - --message-retention-duration=31d

  - name: 'gcr.io/cloud-builders/gcloud'
    id: create-topic-sub-1
    waitFor: ['create-topic-pub-1']
    args:
      - pubsub
      - subscriptions
      - create
      - decrypt-test-1-sink-sub
      - --topic=decrypt-test-1-sink
      - --topic-project=crm-production-335312

  - name: 'gcr.io/cloud-builders/gcloud'
    id: create-topic-pub-2
    waitFor: ['-']
    args:
      - pubsub
      - topics
      - create
      - decrypt-test-2-sink
      - --message-retention-duration=31d

  - name: 'gcr.io/cloud-builders/gcloud'
    id: create-topic-sub-2
    waitFor: ['create-topic-pub-2']
    args:
      - pubsub
      - subscriptions
      - create
      - decrypt-test-2-sink-sub
      - --topic=decrypt-test-2-sink
      - --topic-project=crm-production-335312

  - name: 'gcr.io/cloud-builders/gcloud'
    id: create-topic-pub-3
    waitFor: ['-']
    args:
      - pubsub
      - topics
      - create
      - decrypt-test-3-sink
      - --message-retention-duration=31d

  - name: 'gcr.io/cloud-builders/gcloud'
    id: create-topic-sub-3
    waitFor: ['create-topic-pub-3']
    args:
      - pubsub
      - subscriptions
      - create
      - decrypt-test-3-sink-sub
      - --topic=decrypt-test-3-sink
      - --topic-project=crm-production-335312

  - name: 'gcr.io/cloud-builders/gcloud'
    id: create-topic-pub-4
    waitFor: ['-']
    args:
      - pubsub
      - topics
      - create
      - decrypt-test-4-sink
      - --message-retention-duration=31d

  - name: 'gcr.io/cloud-builders/gcloud'
    id: create-topic-sub-4
    waitFor: ['create-topic-pub-4']
    args:
      - pubsub
      - subscriptions
      - create
      - decrypt-test-4-sink-sub
      - --topic=decrypt-test-4-sink
      - --topic-project=crm-production-335312

  - name: 'gcr.io/cloud-builders/gcloud'
    id: create-topic-pub-5
    waitFor: ['-']
    args:
      - pubsub
      - topics
      - create
      - decrypt-test-5-sink
      - --message-retention-duration=31d

  - name: 'gcr.io/cloud-builders/gcloud'
    id: create-topic-sub-5
    waitFor: ['create-topic-pub-5']
    args:
      - pubsub
      - subscriptions
      - create
      - decrypt-test-5-sink-sub
      - --topic=decrypt-test-5-sink
      - --topic-project=crm-production-335312

  - name: 'gcr.io/cloud-builders/gcloud'
    id: create-topic-pub-6
    waitFor: ['-']
    args:
      - pubsub
      - topics
      - create
      - decrypt-test-6-sink
      - --message-retention-duration=31d

  - name: 'gcr.io/cloud-builders/gcloud'
    id: create-topic-sub-6
    waitFor: ['create-topic-pub-6']
    args:
      - pubsub
      - subscriptions
      - create
      - decrypt-test-6-sink-sub
      - --topic=decrypt-test-6-sink
      - --topic-project=crm-production-335312

  - name: 'gcr.io/cloud-builders/gcloud'
    id: create-topic-pub-7
    waitFor: ['-']
    args:
      - pubsub
      - topics
      - create
      - decrypt-test-7-sink
      - --message-retention-duration=31d

  - name: 'gcr.io/cloud-builders/gcloud'
    id: create-topic-sub-7
    waitFor: ['create-topic-pub-7']
    args:
      - pubsub
      - subscriptions
      - create
      - decrypt-test-7-sink-sub
      - --topic=decrypt-test-7-sink
      - --topic-project=crm-production-335312

  - name: 'gcr.io/cloud-builders/gcloud'
    id: create-topic-pub-8
    waitFor: ['-']
    args:
      - pubsub
      - topics
      - create
      - decrypt-test-8-sink
      - --message-retention-duration=31d

  - name: 'gcr.io/cloud-builders/gcloud'
    id: create-topic-sub-8
    waitFor: ['create-topic-pub-8']
    args:
      - pubsub
      - subscriptions
      - create
      - decrypt-test-8-sink-sub
      - --topic=decrypt-test-8-sink
      - --topic-project=crm-production-335312

  - name: 'gcr.io/cloud-builders/gcloud'
    id: create-topic-pub-9
    waitFor: ['-']
    args:
      - pubsub
      - topics
      - create
      - decrypt-test-9-sink
      - --message-retention-duration=31d

  - name: 'gcr.io/cloud-builders/gcloud'
    id: create-topic-sub-9
    waitFor: ['create-topic-pub-9']
    args:
      - pubsub
      - subscriptions
      - create
      - decrypt-test-9-sink-sub
      - --topic=decrypt-test-9-sink
      - --topic-project=crm-production-335312

  - name: 'gcr.io/cloud-builders/gcloud'
    id: create-topic-pub-10
    waitFor: ['-']
    args:
      - pubsub
      - topics
      - create
      - decrypt-test-10-sink
      - --message-retention-duration=31d

  - name: 'gcr.io/cloud-builders/gcloud'
    id: create-topic-sub-10
    waitFor: ['create-topic-pub-10']
    args:
      - pubsub
      - subscriptions
      - create
      - decrypt-test-10-sink-sub
      - --topic=decrypt-test-10-sink
      - --topic-project=crm-production-335312

  - name: 'gcr.io/cloud-builders/gcloud'
    id: create-topic-pub-11
    args:
      - pubsub
      - topics
      - create
      - decrypt-test-11-sink
      - --message-retention-duration=31d

  - name: 'gcr.io/cloud-builders/gcloud'
    id: create-topic-sub-11
    args:
      - pubsub
      - subscriptions
      - create
      - decrypt-test-11-sink-sub
      - --topic=decrypt-test-11-sink
      - --topic-project=crm-production-335312

  - name: 'gcr.io/cloud-builders/gcloud'
    id: create-topic-pub-12
    waitFor: ['-']
    args:
      - pubsub
      - topics
      - create
      - decrypt-test-12-sink
      - --message-retention-duration=31d

  - name: 'gcr.io/cloud-builders/gcloud'
    id: create-topic-sub-12
    waitFor: ['create-topic-pub-12']
    args:
      - pubsub
      - subscriptions
      - create
      - decrypt-test-12-sink-sub
      - --topic=decrypt-test-12-sink
      - --topic-project=crm-production-335312

  - name: 'gcr.io/cloud-builders/gcloud'
    id: create-topic-pub-13
    waitFor: ['-']
    args:
      - pubsub
      - topics
      - create
      - decrypt-test-13-sink
      - --message-retention-duration=31d

  - name: 'gcr.io/cloud-builders/gcloud'
    id: create-topic-sub-13
    waitFor: ['create-topic-pub-13']
    args:
      - pubsub
      - subscriptions
      - create
      - decrypt-test-13-sink-sub
      - --topic=decrypt-test-13-sink
      - --topic-project=crm-production-335312

  - name: 'gcr.io/cloud-builders/gcloud'
    id: create-topic-pub-14
    waitFor: ['-']
    args:
      - pubsub
      - topics
      - create
      - decrypt-test-14-sink
      - --message-retention-duration=31d

  - name: 'gcr.io/cloud-builders/gcloud'
    id: create-topic-sub-14
    waitFor: ['create-topic-pub-14']
    args:
      - pubsub
      - subscriptions
      - create
      - decrypt-test-14-sink-sub
      - --topic=decrypt-test-14-sink
      - --topic-project=crm-production-335312

  - name: 'gcr.io/cloud-builders/gcloud'
    id: create-topic-pub-15
    waitFor: ['-']
    args:
      - pubsub
      - topics
      - create
      - decrypt-test-15-sink
      - --message-retention-duration=31d

  - name: 'gcr.io/cloud-builders/gcloud'
    id: create-topic-sub-15
    waitFor: ['create-topic-pub-15']
    args:
      - pubsub
      - subscriptions
      - create
      - decrypt-test-15-sink-sub
      - --topic=decrypt-test-15-sink
      - --topic-project=crm-production-335312

  - name: 'gcr.io/cloud-builders/gcloud'
    id: create-topic-pub-16
    waitFor: ['-']
    args:
      - pubsub
      - topics
      - create
      - decrypt-test-16-sink
      - --message-retention-duration=31d

  - name: 'gcr.io/cloud-builders/gcloud'
    id: create-topic-sub-16
    waitFor: ['create-topic-pub-16']
    args:
      - pubsub
      - subscriptions
      - create
      - decrypt-test-16-sink-sub
      - --topic=decrypt-test-16-sink
      - --topic-project=crm-production-335312

  - name: 'gcr.io/cloud-builders/gcloud'
    id: create-topic-pub-17
    waitFor: ['-']
    args:
      - pubsub
      - topics
      - create
      - decrypt-test-17-sink
      - --message-retention-duration=31d

  - name: 'gcr.io/cloud-builders/gcloud'
    id: create-topic-sub-17
    waitFor: ['create-topic-pub-17']
    args:
      - pubsub
      - subscriptions
      - create
      - decrypt-test-17-sink-sub
      - --topic=decrypt-test-17-sink
      - --topic-project=crm-production-335312

  - name: 'gcr.io/cloud-builders/gcloud'
    id: create-topic-pub-18
    waitFor: ['-']
    args:
      - pubsub
      - topics
      - create
      - decrypt-test-18-sink
      - --message-retention-duration=31d

  - name: 'gcr.io/cloud-builders/gcloud'
    id: create-topic-sub-18
    waitFor: ['create-topic-pub-18']
    args:
      - pubsub
      - subscriptions
      - create
      - decrypt-test-18-sink-sub
      - --topic=decrypt-test-18-sink
      - --topic-project=crm-production-335312

  - name: 'gcr.io/cloud-builders/gcloud'
    id: create-topic-pub-19
    waitFor: ['-']
    args:
      - pubsub
      - topics
      - create
      - decrypt-test-19-sink
      - --message-retention-duration=31d

  - name: 'gcr.io/cloud-builders/gcloud'
    id: create-topic-sub-19
    waitFor: ['create-topic-pub-19']
    args:
      - pubsub
      - subscriptions
      - create
      - decrypt-test-19-sink-sub
      - --topic=decrypt-test-19-sink
      - --topic-project=crm-production-335312

  - name: 'gcr.io/cloud-builders/gcloud'
    id: create-topic-pub-20
    waitFor: ['-']
    args:
      - pubsub
      - topics
      - create
      - decrypt-test-20-sink
      - --message-retention-duration=31d

  - name: 'gcr.io/cloud-builders/gcloud'
    id: create-topic-sub-20
    waitFor: ['create-topic-pub-20']
    args:
      - pubsub
      - subscriptions
      - create
      - decrypt-test-20-sink-sub
      - --topic=decrypt-test-20-sink
      - --topic-project=crm-production-335312

  - name: 'gcr.io/cloud-builders/gcloud'
    id: create-topic-pub-21
    args:
      - pubsub
      - topics
      - create
      - decrypt-test-21-sink
      - --message-retention-duration=31d

  - name: 'gcr.io/cloud-builders/gcloud'
    id: create-topic-sub-21
    args:
      - pubsub
      - subscriptions
      - create
      - decrypt-test-21-sink-sub
      - --topic=decrypt-test-21-sink
      - --topic-project=crm-production-335312

  - name: 'gcr.io/cloud-builders/gcloud'
    id: create-topic-pub-22
    waitFor: ['-']
    args:
      - pubsub
      - topics
      - create
      - decrypt-test-22-sink
      - --message-retention-duration=31d

  - name: 'gcr.io/cloud-builders/gcloud'
    id: create-topic-sub-22
    waitFor: ['create-topic-pub-22']
    args:
      - pubsub
      - subscriptions
      - create
      - decrypt-test-22-sink-sub
      - --topic=decrypt-test-22-sink
      - --topic-project=crm-production-335312

  - name: 'gcr.io/cloud-builders/gcloud'
    id: create-topic-pub-23
    waitFor: ['-']
    args:
      - pubsub
      - topics
      - create
      - decrypt-test-23-sink
      - --message-retention-duration=31d

  - name: 'gcr.io/cloud-builders/gcloud'
    id: create-topic-sub-23
    waitFor: ['create-topic-pub-23']
    args:
      - pubsub
      - subscriptions
      - create
      - decrypt-test-23-sink-sub
      - --topic=decrypt-test-23-sink
      - --topic-project=crm-production-335312

  - name: 'gcr.io/cloud-builders/gcloud'
    id: create-topic-pub-24
    waitFor: ['-']
    args:
      - pubsub
      - topics
      - create
      - decrypt-test-24-sink
      - --message-retention-duration=31d

  - name: 'gcr.io/cloud-builders/gcloud'
    id: create-topic-sub-24
    waitFor: ['create-topic-pub-24']
    args:
      - pubsub
      - subscriptions
      - create
      - decrypt-test-24-sink-sub
      - --topic=decrypt-test-24-sink
      - --topic-project=crm-production-335312

  - name: 'gcr.io/cloud-builders/gcloud'
    id: create-topic-pub-25
    waitFor: ['-']
    args:
      - pubsub
      - topics
      - create
      - decrypt-test-25-sink
      - --message-retention-duration=31d

  - name: 'gcr.io/cloud-builders/gcloud'
    id: create-topic-sub-25
    waitFor: ['create-topic-pub-25']
    args:
      - pubsub
      - subscriptions
      - create
      - decrypt-test-25-sink-sub
      - --topic=decrypt-test-25-sink
      - --topic-project=crm-production-335312

  - name: 'gcr.io/cloud-builders/gcloud'
    id: create-topic-pub-26
    waitFor: ['-']
    args:
      - pubsub
      - topics
      - create
      - decrypt-test-26-sink
      - --message-retention-duration=31d

  - name: 'gcr.io/cloud-builders/gcloud'
    id: create-topic-sub-26
    waitFor: ['create-topic-pub-26']
    args:
      - pubsub
      - subscriptions
      - create
      - decrypt-test-26-sink-sub
      - --topic=decrypt-test-26-sink
      - --topic-project=crm-production-335312

  - name: 'gcr.io/cloud-builders/gcloud'
    id: create-topic-pub-27
    waitFor: ['-']
    args:
      - pubsub
      - topics
      - create
      - decrypt-test-27-sink
      - --message-retention-duration=31d

  - name: 'gcr.io/cloud-builders/gcloud'
    id: create-topic-sub-27
    waitFor: ['create-topic-pub-27']
    args:
      - pubsub
      - subscriptions
      - create
      - decrypt-test-27-sink-sub
      - --topic=decrypt-test-27-sink
      - --topic-project=crm-production-335312

  - name: 'gcr.io/cloud-builders/gcloud'
    id: create-topic-pub-28
    waitFor: ['-']
    args:
      - pubsub
      - topics
      - create
      - decrypt-test-28-sink
      - --message-retention-duration=31d

  - name: 'gcr.io/cloud-builders/gcloud'
    id: create-topic-sub-28
    waitFor: ['create-topic-pub-28']
    args:
      - pubsub
      - subscriptions
      - create
      - decrypt-test-28-sink-sub
      - --topic=decrypt-test-28-sink
      - --topic-project=crm-production-335312

  - name: 'gcr.io/cloud-builders/gcloud'
    id: create-topic-pub-29
    waitFor: ['-']
    args:
      - pubsub
      - topics
      - create
      - decrypt-test-29-sink
      - --message-retention-duration=31d

  - name: 'gcr.io/cloud-builders/gcloud'
    id: create-topic-sub-29
    waitFor: ['create-topic-pub-29']
    args:
      - pubsub
      - subscriptions
      - create
      - decrypt-test-29-sink-sub
      - --topic=decrypt-test-29-sink
      - --topic-project=crm-production-335312

  - name: 'gcr.io/cloud-builders/gcloud'
    id: create-topic-pub-30
    waitFor: ['-']
    args:
      - pubsub
      - topics
      - create
      - decrypt-test-30-sink
      - --message-retention-duration=31d

  - name: 'gcr.io/cloud-builders/gcloud'
    id: create-topic-sub-30
    waitFor: ['create-topic-pub-30']
    args:
      - pubsub
      - subscriptions
      - create
      - decrypt-test-30-sink-sub
      - --topic=decrypt-test-30-sink
      - --topic-project=crm-production-335312
