steps:
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bq'
    id: create-bq-cltv-propensity-table
    args:
      - query
      - --destination_table=aixp_cltv_decryption.cltv_prop
      - --use_legacy_sql=false
      - SELECT *, RAND() AS consumer_id FROM `crm-production-335312`.aixp_experiment_prod.cltv_propensity_prediction WHERE original_timestamp > TIMESTAMP(DATE_TRUNC(CURRENT_DATE('Asia/Jakarta'), MONTH) - 1)

  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bq'
    id: create-bq-cltv-propensity-table-1
    args:
      - query
      - --destination_table=aixp_cltv_decryption.cltv_prop_1
      - --use_legacy_sql=false
      - 'SELECT * FROM `crm-production-335312`.aixp_cltv_decryption.cltv_prop WHERE consumer_id < 0.25'

  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bq'
    id: create-bq-cltv-propensity-table-2
    args:
      - query
      - --destination_table=aixp_cltv_decryption.cltv_prop_2
      - --use_legacy_sql=false
      - 'SELECT * FROM `crm-production-335312`.aixp_cltv_decryption.cltv_prop WHERE consumer_id >= 0.25 and consumer_id < 0.5'

  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bq'
    id: create-bq-cltv-propensity-table-3
    args:
      - query
      - --destination_table=aixp_cltv_decryption.cltv_prop_3
      - --use_legacy_sql=false
      - 'SELECT * FROM `crm-production-335312`.aixp_cltv_decryption.cltv_prop WHERE consumer_id >= 0.5 and consumer_id < 0.75'

  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bq'
    id: create-bq-cltv-propensity-table-4
    args:
      - query
      - --destination_table=aixp_cltv_decryption.cltv_prop_4
      - --use_legacy_sql=false
      - 'SELECT * FROM `crm-production-335312`.aixp_cltv_decryption.cltv_prop WHERE consumer_id >= 0.75'

  - name: 'gcr.io/cloud-builders/gcloud'
    id: deploy-decryption-function-cltv-prop
    args:
      - functions
      - deploy
      - decryption-function-cltv-prop
      - --runtime=python38
      - --entry-point=hello_pubsub
      - --source=gs://decryption-function/cltv/source-cltv.zip
      - --trigger-topic=trigger-topic-customerLifetimeValueProp
      - --allow-unauthenticated
      - --region=asia-southeast2
      - --timeout=300s
      - --memory=1024MB

  - name: 'ubuntu'
    args: ['sleep', '120']

  - name: 'gcr.io/cloud-builders/gcloud'
    id: create-dataflow-job-cltv-prop-1
    args:
      - dataflow
      - sql
      - query
      - SELECT *, 11 AS batch, ['nik', 'nik_or_phone', 'phone_number'] AS encrypted_cols, ['original_timestamp'] AS date_cols FROM bigquery.table.`crm-production-335312`.aixp_cltv_decryption.cltv_prop_1
      - --job-name=cltv-prop-1
      - --pubsub-topic=trigger-topic-customerLifetimeValueProp
      - --region=asia-southeast2

  - name: 'ubuntu'
    args: ['sleep', '720']

  - name: 'gcr.io/cloud-builders/gcloud'
    id: create-dataflow-job-cltv-prop-2
    args:
      - dataflow
      - sql
      - query
      - SELECT *, 12 AS batch, ['nik', 'nik_or_phone', 'phone_number'] AS encrypted_cols, ['original_timestamp'] AS date_cols FROM bigquery.table.`crm-production-335312`.aixp_cltv_decryption.cltv_prop_2
      - --job-name=cltv-prop-2
      - --pubsub-topic=trigger-topic-customerLifetimeValueProp
      - --region=asia-southeast2

  - name: 'ubuntu'
    args: ['sleep', '720']

  - name: 'gcr.io/cloud-builders/gcloud'
    id: create-dataflow-job-cltv-prop-3
    args:
      - dataflow
      - sql
      - query
      - SELECT *, 13 AS batch, ['nik', 'nik_or_phone', 'phone_number'] AS encrypted_cols, ['original_timestamp'] AS date_cols FROM bigquery.table.`crm-production-335312`.aixp_cltv_decryption.cltv_prop_3
      - --job-name=cltv-prop-3
      - --pubsub-topic=trigger-topic-customerLifetimeValueProp
      - --region=asia-southeast2

  - name: 'ubuntu'
    args: ['sleep', '720']

  - name: 'gcr.io/cloud-builders/gcloud'
    id: create-dataflow-job-cltv-prop-4
    args:
      - dataflow
      - sql
      - query
      - SELECT *, 14 AS batch, ['nik', 'nik_or_phone', 'phone_number'] AS encrypted_cols, ['original_timestamp'] AS date_cols FROM bigquery.table.`crm-production-335312`.aixp_cltv_decryption.cltv_prop_4
      - --job-name=cltv-prop-3
      - --pubsub-topic=trigger-topic-customerLifetimeValueProp
      - --region=asia-southeast2

  - name: 'ubuntu'
    args: ['sleep', '720']

  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bq'
    id: create-bq-cltv-calculation-table
    args:
      - query
      - --destination_table=aixp_cltv_decryption.cltv
      - --use_legacy_sql=false
      - SELECT *, RAND() AS consumer_id FROM `crm-production-335312`.aixp_ml_prod.cltv_calculation_table WHERE original_timestamp > TIMESTAMP(DATE_TRUNC(CURRENT_DATE('Asia/Jakarta'), MONTH) - 1)

  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bq'
    id: create-bq-cltv-calculation-table-1
    args:
      - query
      - --destination_table=aixp_cltv_decryption.cltv_1
      - --use_legacy_sql=false
      - 'SELECT * FROM `crm-production-335312`.aixp_cltv_decryption.cltv WHERE consumer_id < 0.5'

  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bq'
    id: create-bq-cltv-calculation-table-2
    waitFor: ['create-bq-cltv-calculation-table']
    args:
      - query
      - --destination_table=aixp_cltv_decryption.cltv_2
      - --use_legacy_sql=false
      - 'SELECT * FROM `crm-production-335312`.aixp_cltv_decryption.cltv WHERE consumer_id >= 0.5'

  - name: 'gcr.io/cloud-builders/gcloud'
    id: delete-deployed-function-cltv-prop
    args:
      - functions
      - delete
      - decryption-function-cltv-prop
      - --region=asia-southeast2

  - name: 'gcr.io/cloud-builders/gcloud'
    id: deploy-decryption-function-cltv
    args:
      - functions
      - deploy
      - decryption-function-cltv
      - --runtime=python38
      - --entry-point=hello_pubsub
      - --source=gs://decryption-function/cltv/source-cltv.zip
      - --trigger-topic=trigger-topic-customerLifetimeValue
      - --allow-unauthenticated
      - --region=asia-southeast2
      - --timeout=300s
      - --memory=1024MB

  - name: 'ubuntu'
    args: ['sleep', '120']

  - name: 'gcr.io/cloud-builders/gcloud'
    id: create-dataflow-job-cltv-1
    args:
      - dataflow
      - sql
      - query
      - SELECT *, 1 AS batch, ['nik', 'nik_or_phone', 'phone_number'] AS encrypted_cols, ['original_timestamp'] AS date_cols FROM bigquery.table.`crm-production-335312`.aixp_cltv_decryption.cltv_1 WHERE consumer_id < 0.1
      - --job-name=cltv-1
      - --pubsub-topic=trigger-topic-customerLifetimeValue
      - --region=asia-southeast2

  - name: 'ubuntu'
    args: ['sleep', '720']

  - name: 'gcr.io/cloud-builders/gcloud'
    id: create-dataflow-job-cltv-2
    args:
      - dataflow
      - sql
      - query
      - SELECT *, 2 AS batch, ['nik', 'nik_or_phone', 'phone_number'] AS encrypted_cols, ['original_timestamp'] AS date_cols FROM bigquery.table.`crm-production-335312`.aixp_cltv_decryption.cltv_1 WHERE consumer_id >= 0.1 and consumer_id < 0.2
      - --job-name=cltv-2
      - --pubsub-topic=trigger-topic-customerLifetimeValue
      - --region=asia-southeast2

  - name: 'ubuntu'
    args: ['sleep', '720']

  - name: 'gcr.io/cloud-builders/gcloud'
    id: create-dataflow-job-cltv-3
    args:
      - dataflow
      - sql
      - query
      - SELECT *, 3 AS batch, ['nik', 'nik_or_phone', 'phone_number'] AS encrypted_cols, ['original_timestamp'] AS date_cols FROM bigquery.table.`crm-production-335312`.aixp_cltv_decryption.cltv_1 WHERE consumer_id >= 0.2 and consumer_id < 0.3
      - --job-name=cltv-3
      - --pubsub-topic=trigger-topic-customerLifetimeValue
      - --region=asia-southeast2

  - name: 'ubuntu'
    args: ['sleep', '720']

  - name: 'gcr.io/cloud-builders/gcloud'
    id: create-dataflow-job-cltv-4
    args:
      - dataflow
      - sql
      - query
      - SELECT *, 4 AS batch, ['nik', 'nik_or_phone', 'phone_number'] AS encrypted_cols, ['original_timestamp'] AS date_cols FROM bigquery.table.`crm-production-335312`.aixp_cltv_decryption.cltv_1 WHERE consumer_id >= 0.3 and consumer_id < 0.4
      - --job-name=cltv-4
      - --pubsub-topic=trigger-topic-customerLifetimeValue
      - --region=asia-southeast2

  - name: 'ubuntu'
    args: ['sleep', '720']

  - name: 'gcr.io/cloud-builders/gcloud'
    id: create-dataflow-job-cltv-5
    args:
      - dataflow
      - sql
      - query
      - SELECT *, 5 AS batch, ['nik', 'nik_or_phone', 'phone_number'] AS encrypted_cols, ['original_timestamp'] AS date_cols FROM bigquery.table.`crm-production-335312`.aixp_cltv_decryption.cltv_1 WHERE consumer_id >= 0.4 and consumer_id < 0.5
      - --job-name=cltv-5
      - --pubsub-topic=trigger-topic-customerLifetimeValue
      - --region=asia-southeast2

  - name: 'ubuntu'
    args: ['sleep', '720']

  - name: 'gcr.io/cloud-builders/gcloud'
    id: create-dataflow-job-cltv-6
    args:
      - dataflow
      - sql
      - query
      - SELECT *, 6 AS batch, ['nik', 'nik_or_phone', 'phone_number'] AS encrypted_cols, ['original_timestamp'] AS date_cols FROM bigquery.table.`crm-production-335312`.aixp_cltv_decryption.cltv_2 WHERE consumer_id >= 0.5 and consumer_id < 0.6
      - --job-name=cltv-6
      - --pubsub-topic=trigger-topic-customerLifetimeValue
      - --region=asia-southeast2

  - name: 'ubuntu'
    args: ['sleep', '720']

  - name: 'gcr.io/cloud-builders/gcloud'
    id: create-dataflow-job-cltv-7
    args:
      - dataflow
      - sql
      - query
      - SELECT *, 7 AS batch, ['nik', 'nik_or_phone', 'phone_number'] AS encrypted_cols, ['original_timestamp'] AS date_cols FROM bigquery.table.`crm-production-335312`.aixp_cltv_decryption.cltv_2 WHERE consumer_id >= 0.6 and consumer_id < 0.7
      - --job-name=cltv-7
      - --pubsub-topic=trigger-topic-customerLifetimeValue
      - --region=asia-southeast2

  - name: 'ubuntu'
    args: ['sleep', '720']

  - name: 'gcr.io/cloud-builders/gcloud'
    id: create-dataflow-job-cltv-8
    args:
      - dataflow
      - sql
      - query
      - SELECT *, 8 AS batch, ['nik', 'nik_or_phone', 'phone_number'] AS encrypted_cols, ['original_timestamp'] AS date_cols FROM bigquery.table.`crm-production-335312`.aixp_cltv_decryption.cltv_2 WHERE consumer_id >= 0.7 and consumer_id < 0.8
      - --job-name=cltv-8
      - --pubsub-topic=trigger-topic-customerLifetimeValue
      - --region=asia-southeast2

  - name: 'ubuntu'
    args: ['sleep', '720']

  - name: 'gcr.io/cloud-builders/gcloud'
    id: create-dataflow-job-cltv-9
    args:
      - dataflow
      - sql
      - query
      - SELECT *, 9 AS batch, ['nik', 'nik_or_phone', 'phone_number'] AS encrypted_cols, ['original_timestamp'] AS date_cols FROM bigquery.table.`crm-production-335312`.aixp_cltv_decryption.cltv_2 WHERE consumer_id >= 0.8 and consumer_id < 0.9
      - --job-name=cltv-9
      - --pubsub-topic=trigger-topic-customerLifetimeValue
      - --region=asia-southeast2

  - name: 'ubuntu'
    args: ['sleep', '720']

  - name: 'gcr.io/cloud-builders/gcloud'
    id: create-dataflow-job-cltv-10
    args:
      - dataflow
      - sql
      - query
      - SELECT *, 10 AS batch, ['nik', 'nik_or_phone', 'phone_number'] AS encrypted_cols, ['original_timestamp'] AS date_cols FROM bigquery.table.`crm-production-335312`.aixp_cltv_decryption.cltv_2 WHERE consumer_id >= 0.9
      - --job-name=cltv-10
      - --pubsub-topic=trigger-topic-customerLifetimeValue
      - --region=asia-southeast2

  - name: 'ubuntu'
    args: ['sleep', '1200']

  - name: 'gcr.io/cloud-builders/gcloud'
    id: delete-deployed-function-cltv
    args:
      - functions
      - delete
      - decryption-function-cltv
      - --region=asia-southeast2

timeout: 36000s
