steps:
- name: 'gcr.io/cloud-builders/gcloud'
  id: deploy-decryption-function
  args:
  - functions
  - deploy
  - decryption-function
  - --runtime=python38
  - --entry-point=hello_pubsub 
  - --source=gs://test-decryption-function/source/source.zip
  - --trigger-topic=trigger-topic-customerLifetimeValueProp
  - --allow-unauthenticated
  - --region=asia-southeast2
  - --timeout=300s

- name: 'gcr.io/cloud-builders/gcloud'
  id: create-dataflow-job
  waitFor: ['deploy-decryption-function']
  args:
  - dataflow
  - sql
  - query
  - SELECT * EXCEPT(rnd), ['nik', 'nik_or_phone', 'phone_number'] AS encrypted_cols, ['original_timestamp'] AS date_cols FROM bigquery.table.`crm-production-335312`.aixp_experiment_dev cltv_propensity_prediction_rnd  WHERE rnd >= 0 and rnd < 0.1 LIMIT 12000x
  - --job-name=cltv-test
  - --pubsub-topic=trigger-topic-customerLifetimeValue
  - --region=asia-southeast2

- name: 'gcr.io/cloud-builders/gcloud'
  id: delete-deployed-function
  waitFor: ['create-dataflow-job']
  args:
  - functions
  - delete
  - decryption-function
  - --region=asia-southeast2


